apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-credentials
  labels:
    app: mlflow
type: Opaque
stringData:
  db.host: "postgresql"
  db.port: "5432"
  db.name: "mlflow"
  db.user: "postgres"
  db.password: "postgres123"
