apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
type: Opaque
stringData:
  db.host: "postgresql"
  db.port: "5432"
  db.name: "postgres"
  db.user: "postgres"
  db.password: "postgres123"
