// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 7ea37f5208cc0fc8e16933941e91c7a85bf61e94b0e4f7c8b1d4de918122a5a1
// Generated: 2026-06-29T17:10:10Z

package types

type ListOptions struct {
	Page    int
	Size    int
	Search  string
	OrderBy string
	Fields  string
}

type ListOptionsBuilder struct {
	opts ListOptions
}

func NewListOptions() *ListOptionsBuilder {
	return &ListOptionsBuilder{opts: ListOptions{Page: 1, Size: 100}}
}

func (b *ListOptionsBuilder) Page(page int) *ListOptionsBuilder {
	b.opts.Page = page
	return b
}

func (b *ListOptionsBuilder) Size(size int) *ListOptionsBuilder {
	if size > 65500 {
		size = 65500
	}
	b.opts.Size = size
	return b
}

func (b *ListOptionsBuilder) Search(search string) *ListOptionsBuilder {
	b.opts.Search = search
	return b
}

func (b *ListOptionsBuilder) OrderBy(orderBy string) *ListOptionsBuilder {
	b.opts.OrderBy = orderBy
	return b
}

func (b *ListOptionsBuilder) Fields(fields string) *ListOptionsBuilder {
	b.opts.Fields = fields
	return b
}

func (b *ListOptionsBuilder) Build() *ListOptions {
	return &b.opts
}
