// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 89525e5916970f7b5a70897b81a525c7f51fadbe26a4fb887b245fd819f97156
// Generated: 2026-09-09T16:09:51Z

package types

import (
	"errors"
	"fmt"
)

type Project struct {
	ObjectReference

	Annotations              string `json:"annotations,omitempty"`
	Description              string `json:"description,omitempty"`
	GatewayAccountExpiresAt  string `json:"gateway_account_expires_at,omitempty"`
	GatewayAccountID         string `json:"gateway_account_id,omitempty"`
	GatewayCredentialID      string `json:"gateway_credential_id,omitempty"`
	GatewayEndpoint          string `json:"gateway_endpoint,omitempty"`
	GatewayError             string `json:"gateway_error,omitempty"`
	GatewayExternalReference string `json:"gateway_external_reference,omitempty"`
	GatewayID                string `json:"gateway_id,omitempty"`
	GatewayInstanceID        string `json:"gateway_instance_id,omitempty"`
	GatewayStatus            string `json:"gateway_status,omitempty"`
	Labels                   string `json:"labels,omitempty"`
	Name                     string `json:"name"`
	Prompt                   string `json:"prompt,omitempty"`
	RuntimeBackend           string `json:"runtime_backend,omitempty"`
	RuntimeDeleted           bool   `json:"runtime_deleted,omitempty"`
	RuntimeVersion           int    `json:"runtime_version,omitempty"`
	Status                   string `json:"status,omitempty"`
}

type ProjectList struct {
	ListMeta
	Items []Project `json:"items"`
}

func (l *ProjectList) GetItems() []Project { return l.Items }
func (l *ProjectList) GetTotal() int       { return l.Total }
func (l *ProjectList) GetPage() int        { return l.Page }
func (l *ProjectList) GetSize() int        { return l.Size }

type ProjectBuilder struct {
	resource Project
	errors   []error
}

func NewProjectBuilder() *ProjectBuilder {
	return &ProjectBuilder{}
}

func (b *ProjectBuilder) Annotations(v string) *ProjectBuilder {
	b.resource.Annotations = v
	return b
}

func (b *ProjectBuilder) Description(v string) *ProjectBuilder {
	b.resource.Description = v
	return b
}

func (b *ProjectBuilder) Labels(v string) *ProjectBuilder {
	b.resource.Labels = v
	return b
}

func (b *ProjectBuilder) Name(v string) *ProjectBuilder {
	b.resource.Name = v
	return b
}

func (b *ProjectBuilder) Prompt(v string) *ProjectBuilder {
	b.resource.Prompt = v
	return b
}

func (b *ProjectBuilder) Status(v string) *ProjectBuilder {
	b.resource.Status = v
	return b
}

func (b *ProjectBuilder) Build() (*Project, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ProjectPatchBuilder struct {
	patch map[string]any
}

func NewProjectPatchBuilder() *ProjectPatchBuilder {
	return &ProjectPatchBuilder{patch: make(map[string]any)}
}

func (b *ProjectPatchBuilder) Annotations(v string) *ProjectPatchBuilder {
	b.patch["annotations"] = v
	return b
}

func (b *ProjectPatchBuilder) Description(v string) *ProjectPatchBuilder {
	b.patch["description"] = v
	return b
}

func (b *ProjectPatchBuilder) Labels(v string) *ProjectPatchBuilder {
	b.patch["labels"] = v
	return b
}

func (b *ProjectPatchBuilder) Name(v string) *ProjectPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *ProjectPatchBuilder) Prompt(v string) *ProjectPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *ProjectPatchBuilder) Status(v string) *ProjectPatchBuilder {
	b.patch["status"] = v
	return b
}

func (b *ProjectPatchBuilder) Build() map[string]any {
	return b.patch
}
