// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: b2f4659285c47d15f89149857d020711a05eacfee25e684f7e09207fd5f178e3
// Generated: 2026-07-16T03:55:12Z

package types

import (
	"errors"
	"fmt"
	"time"
)

type SessionEvent struct {
	ObjectReference

	CompletedAt *time.Time `json:"completed_at,omitempty"`
	EventCount  int32      `json:"event_count,omitempty"`
	EventType   string     `json:"event_type,omitempty"`
	Payload     string     `json:"payload,omitempty"`
	Seq         int        `json:"seq,omitempty"`
	SessionID   string     `json:"session_id,omitempty"`
}

type SessionEventList struct {
	ListMeta
	Items []SessionEvent `json:"items"`
}

func (l *SessionEventList) GetItems() []SessionEvent { return l.Items }
func (l *SessionEventList) GetTotal() int            { return l.Total }
func (l *SessionEventList) GetPage() int             { return l.Page }
func (l *SessionEventList) GetSize() int             { return l.Size }

type SessionEventBuilder struct {
	resource SessionEvent
	errors   []error
}

func NewSessionEventBuilder() *SessionEventBuilder {
	return &SessionEventBuilder{}
}

func (b *SessionEventBuilder) EventType(v string) *SessionEventBuilder {
	b.resource.EventType = v
	return b
}

func (b *SessionEventBuilder) Payload(v string) *SessionEventBuilder {
	b.resource.Payload = v
	return b
}

func (b *SessionEventBuilder) Build() (*SessionEvent, error) {
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type SessionEventPatchBuilder struct {
	patch map[string]any
}

func NewSessionEventPatchBuilder() *SessionEventPatchBuilder {
	return &SessionEventPatchBuilder{patch: make(map[string]any)}
}

func (b *SessionEventPatchBuilder) Build() map[string]any {
	return b.patch
}
