// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: e8cbbb1535c7371667f381a83063a8e31ff4b13a28b782fef206b62a4e61f750
// Generated: 2026-07-02T20:49:37Z

package types

import (
	"errors"
	"fmt"
)

type SessionMessage struct {
	ObjectReference

	EventType string `json:"event_type,omitempty"`
	Payload   string `json:"payload,omitempty"`
	Seq       int    `json:"seq,omitempty"`
	SessionID string `json:"session_id,omitempty"`
}

type SessionMessageList struct {
	ListMeta
	Items []SessionMessage `json:"items"`
}

func (l *SessionMessageList) GetItems() []SessionMessage { return l.Items }
func (l *SessionMessageList) GetTotal() int              { return l.Total }
func (l *SessionMessageList) GetPage() int               { return l.Page }
func (l *SessionMessageList) GetSize() int               { return l.Size }

type SessionMessageBuilder struct {
	resource SessionMessage
	errors   []error
}

func NewSessionMessageBuilder() *SessionMessageBuilder {
	return &SessionMessageBuilder{}
}

func (b *SessionMessageBuilder) EventType(v string) *SessionMessageBuilder {
	b.resource.EventType = v
	return b
}

func (b *SessionMessageBuilder) Payload(v string) *SessionMessageBuilder {
	b.resource.Payload = v
	return b
}

func (b *SessionMessageBuilder) Build() (*SessionMessage, error) {
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type SessionMessagePatchBuilder struct {
	patch map[string]any
}

func NewSessionMessagePatchBuilder() *SessionMessagePatchBuilder {
	return &SessionMessagePatchBuilder{patch: make(map[string]any)}
}

func (b *SessionMessagePatchBuilder) Build() map[string]any {
	return b.patch
}
