kind: Kustomization
resources:
  - agents/hello-world.yaml
  - agents/repo-clone-workspace.yaml
  - agents/security-reviewer.yaml
  - agents/jira-simple-whoami.yaml
  - agents/jira-simple-whoami-with-skill-payload.yaml
  - agents/pr-reviewer.yaml
  - agents/jira-issue-categorizer.yaml
  - agents/test-agent-no-providers.yaml
  - providers/vertex.yaml
  - providers/github.yaml
  - providers/jira.yaml
