apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambient-api-server-db
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgresql
        image: registry.redhat.io/rhel10/postgresql-16:10.1
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: ambient-api-server-db
              key: db.user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ambient-api-server-db
              key: db.password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: ambient-api-server-db
              key: db.name
        volumeMounts:
        - name: ambient-api-server-db-data
          mountPath: /var/lib/pgsql/data
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
