apiVersion: v1
kind: Secret
metadata:
  name: github-app-secret
  labels:
    app: vteam-e2e
type: Opaque
stringData:
  GITHUB_APP_ID: ""
  GITHUB_PRIVATE_KEY: ""
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  GITHUB_STATE_SECRET: "test-state-secret-for-e2e"
