# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: f3ff5127b86e318a0f027ecace131ff4855078252e9789a002100f97ef433e8c
# Generated: 2026-07-15T19:18:14Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .cluster import Cluster, ClusterList

if TYPE_CHECKING:
    from .client import AmbientClient


class ClusterAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> Cluster:
        resp = self._client._request("POST", "/clusters", json=data)
        return Cluster.from_dict(resp)

    def get(self, resource_id: str) -> Cluster:
        resp = self._client._request("GET", f"/clusters/{resource_id}")
        return Cluster.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> ClusterList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/clusters", params=params)
        return ClusterList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> Cluster:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/clusters/{resource_id}", json=data)
        return Cluster.from_dict(resp)

    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"/clusters/{resource_id}", expect_json=False)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Cluster]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
