# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: b033e32bec23ae0f0443bfe66148d0e29b42fa6bb0223ab012bdaf2860a2858e
# Generated: 2026-07-07T12:19:25Z

from __future__ import annotations

from typing import Any, Callable, Iterator, TypeVar

T = TypeVar("T")


def paginate(fetch_page: Callable[..., Any], size: int = 100) -> Iterator[Any]:
    page = 1
    while True:
        result = fetch_page(page=page, size=size)
        yield from result.items
        if page * size >= result.total:
            break
        page += 1
