# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 7ea37f5208cc0fc8e16933941e91c7a85bf61e94b0e4f7c8b1d4de918122a5a1
# Generated: 2026-06-29T17:10:10Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING
from urllib.parse import quote

from ._base import ListOptions
from .session_message import SessionMessage, SessionMessageList

if TYPE_CHECKING:
    from .client import AmbientClient


class SessionMessageAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client
    def _base_path(self) -> str:
        return "/sessions/{id}/messages".replace("{id}", quote(self._client._project, safe=""))


    def create(self, data: dict) -> SessionMessage:
        resp = self._client._request("POST", self._base_path(), json=data)
        return SessionMessage.from_dict(resp)

    def get(self, resource_id: str) -> SessionMessage:
        resp = self._client._request("GET", f"{self._base_path()}/{resource_id}")
        return SessionMessage.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> SessionMessageList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", self._base_path(), params=params)
        return SessionMessageList.from_dict(resp)
    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[SessionMessage]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
