# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 0d99d538cf2137af9c98c3b852de4b2c46377626d7f163abfb3af9423cad7afa
# Generated: 2026-07-08T01:48:22Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class GatewayOidc:
    issuer: str = ""
    audience: str = ""
    jwks_ttl: int = 0
    roles_claim: str = ""
    admin_role: str = ""
    user_role: str = ""
    scopes_claim: str = ""

    @classmethod
    def from_dict(cls, data: Optional[dict]) -> Optional[GatewayOidc]:
        if not data:
            return None
        return cls(
            issuer=data.get("issuer", ""),
            audience=data.get("audience", ""),
            jwks_ttl=data.get("jwks_ttl", 0),
            roles_claim=data.get("roles_claim", ""),
            admin_role=data.get("admin_role", ""),
            user_role=data.get("user_role", ""),
            scopes_claim=data.get("scopes_claim", ""),
        )

    def to_dict(self) -> dict:
        d: dict[str, Any] = {}
        if self.issuer:
            d["issuer"] = self.issuer
        if self.audience:
            d["audience"] = self.audience
        if self.jwks_ttl:
            d["jwks_ttl"] = self.jwks_ttl
        if self.roles_claim:
            d["roles_claim"] = self.roles_claim
        if self.admin_role:
            d["admin_role"] = self.admin_role
        if self.user_role:
            d["user_role"] = self.user_role
        if self.scopes_claim:
            d["scopes_claim"] = self.scopes_claim
        return d


@dataclass(frozen=True)
class Gateway:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    annotations: str = ""
    config: str = ""
    image: str = ""
    labels: str = ""
    name: str = ""
    oidc: Optional[GatewayOidc] = None
    project_id: str = ""
    server_dns_names: list[str] = ""

    @classmethod
    def from_dict(cls, data: dict) -> Gateway:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            annotations=data.get("annotations", ""),
            config=data.get("config", ""),
            image=data.get("image", ""),
            labels=data.get("labels", ""),
            name=data.get("name", ""),
            oidc=GatewayOidc.from_dict(data.get("oidc")),
            project_id=data.get("project_id", ""),
            server_dns_names=data.get("server_dns_names", ""),
        )

    @classmethod
    def builder(cls) -> GatewayBuilder:
        return GatewayBuilder()


@dataclass(frozen=True)
class GatewayList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Gateway] = ()

    @classmethod
    def from_dict(cls, data: dict) -> GatewayList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Gateway.from_dict(item) for item in data.get("items", [])],
        )


class GatewayBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> GatewayBuilder:
        self._data["annotations"] = value
        return self

    def config(self, value: str) -> GatewayBuilder:
        self._data["config"] = value
        return self

    def image(self, value: str) -> GatewayBuilder:
        self._data["image"] = value
        return self

    def labels(self, value: str) -> GatewayBuilder:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> GatewayBuilder:
        self._data["name"] = value
        return self

    def project_id(self, value: str) -> GatewayBuilder:
        self._data["project_id"] = value
        return self

    def oidc(self, value: GatewayOidc) -> GatewayBuilder:
        self._data["oidc"] = value.to_dict()
        return self

    def server_dns_names(self, value: list[str]) -> GatewayBuilder:
        self._data["server_dns_names"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        if "project_id" not in self._data:
            raise ValueError("project_id is required")
        return dict(self._data)


class GatewayPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> GatewayPatch:
        self._data["annotations"] = value
        return self

    def config(self, value: str) -> GatewayPatch:
        self._data["config"] = value
        return self

    def image(self, value: str) -> GatewayPatch:
        self._data["image"] = value
        return self

    def labels(self, value: str) -> GatewayPatch:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> GatewayPatch:
        self._data["name"] = value
        return self

    def oidc(self, value: GatewayOidc) -> GatewayPatch:
        self._data["oidc"] = value.to_dict()
        return self

    def server_dns_names(self, value: list[str]) -> GatewayPatch:
        self._data["server_dns_names"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
