# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 89525e5916970f7b5a70897b81a525c7f51fadbe26a4fb887b245fd819f97156
# Generated: 2026-09-09T16:09:51Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Project:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    annotations: str = ""
    description: str = ""
    gateway_account_expires_at: str = ""
    gateway_account_id: str = ""
    gateway_credential_id: str = ""
    gateway_endpoint: str = ""
    gateway_error: str = ""
    gateway_external_reference: str = ""
    gateway_id: str = ""
    gateway_instance_id: str = ""
    gateway_status: str = ""
    labels: str = ""
    name: str = ""
    prompt: str = ""
    runtime_backend: str = ""
    runtime_deleted: bool = False
    runtime_version: int = 0
    status: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Project:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            annotations=data.get("annotations", ""),
            description=data.get("description", ""),
            gateway_account_expires_at=data.get("gateway_account_expires_at", ""),
            gateway_account_id=data.get("gateway_account_id", ""),
            gateway_credential_id=data.get("gateway_credential_id", ""),
            gateway_endpoint=data.get("gateway_endpoint", ""),
            gateway_error=data.get("gateway_error", ""),
            gateway_external_reference=data.get("gateway_external_reference", ""),
            gateway_id=data.get("gateway_id", ""),
            gateway_instance_id=data.get("gateway_instance_id", ""),
            gateway_status=data.get("gateway_status", ""),
            labels=data.get("labels", ""),
            name=data.get("name", ""),
            prompt=data.get("prompt", ""),
            runtime_backend=data.get("runtime_backend", ""),
            runtime_deleted=data.get("runtime_deleted", False),
            runtime_version=data.get("runtime_version", 0),
            status=data.get("status", ""),
        )

    @classmethod
    def builder(cls) -> ProjectBuilder:
        return ProjectBuilder()


@dataclass(frozen=True)
class ProjectList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Project] = ()

    @classmethod
    def from_dict(cls, data: dict) -> ProjectList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Project.from_dict(item) for item in data.get("items", [])],
        )


class ProjectBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ProjectBuilder:
        self._data["annotations"] = value
        return self

    def description(self, value: str) -> ProjectBuilder:
        self._data["description"] = value
        return self

    def labels(self, value: str) -> ProjectBuilder:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ProjectBuilder:
        self._data["name"] = value
        return self

    def prompt(self, value: str) -> ProjectBuilder:
        self._data["prompt"] = value
        return self

    def status(self, value: str) -> ProjectBuilder:
        self._data["status"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        return dict(self._data)


class ProjectPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ProjectPatch:
        self._data["annotations"] = value
        return self

    def description(self, value: str) -> ProjectPatch:
        self._data["description"] = value
        return self

    def labels(self, value: str) -> ProjectPatch:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ProjectPatch:
        self._data["name"] = value
        return self

    def prompt(self, value: str) -> ProjectPatch:
        self._data["prompt"] = value
        return self

    def status(self, value: str) -> ProjectPatch:
        self._data["status"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
