apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambient-ui
spec:
  template:
    spec:
      containers:
        - name: ambient-ui
          env:
            - name: API_SERVER_URL
              value: http://ambient-api-server:8000
            - name: CONTROL_PLANE_URL
              value: http://ambient-control-plane:8080
            - name: NODE_EXTRA_CA_CERTS
              value: ""
