apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: ambient-dev
data:
  namespaces: |
    - name: ambient-dev
      gateway:
        image: ghcr.io/nvidia/openshell/gateway:0.0.78
        serverDnsNames:
          - openshell-gateway.ambient-dev.svc.cluster.local
