/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GatewayDatabase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayDatabase{}

// GatewayDatabase Database backend configuration for the gateway
type GatewayDatabase struct {
	// Database backend: sqlite, postgres
	Type string `json:"type"`
	// PVC storage request for PostgreSQL data volume (default 5Gi)
	StorageSize *string `json:"storage_size,omitempty"`
	// PostgreSQL container image (default postgres:16)
	Image *string `json:"image,omitempty"`
	// Reserved for future use: name of a K8s Secret with a url key
	ExternalSecretRef *string `json:"external_secret_ref,omitempty"`
}

type _GatewayDatabase GatewayDatabase

// NewGatewayDatabase instantiates a new GatewayDatabase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayDatabase(type_ string) *GatewayDatabase {
	this := GatewayDatabase{}
	this.Type = type_
	var storageSize string = "5Gi"
	this.StorageSize = &storageSize
	var image string = "postgres:16"
	this.Image = &image
	return &this
}

// NewGatewayDatabaseWithDefaults instantiates a new GatewayDatabase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayDatabaseWithDefaults() *GatewayDatabase {
	this := GatewayDatabase{}
	var storageSize string = "5Gi"
	this.StorageSize = &storageSize
	var image string = "postgres:16"
	this.Image = &image
	return &this
}

// GetType returns the Type field value
func (o *GatewayDatabase) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GatewayDatabase) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GatewayDatabase) SetType(v string) {
	o.Type = v
}

// GetStorageSize returns the StorageSize field value if set, zero value otherwise.
func (o *GatewayDatabase) GetStorageSize() string {
	if o == nil || IsNil(o.StorageSize) {
		var ret string
		return ret
	}
	return *o.StorageSize
}

// GetStorageSizeOk returns a tuple with the StorageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayDatabase) GetStorageSizeOk() (*string, bool) {
	if o == nil || IsNil(o.StorageSize) {
		return nil, false
	}
	return o.StorageSize, true
}

// HasStorageSize returns a boolean if a field has been set.
func (o *GatewayDatabase) HasStorageSize() bool {
	if o != nil && !IsNil(o.StorageSize) {
		return true
	}

	return false
}

// SetStorageSize gets a reference to the given string and assigns it to the StorageSize field.
func (o *GatewayDatabase) SetStorageSize(v string) {
	o.StorageSize = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *GatewayDatabase) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayDatabase) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *GatewayDatabase) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *GatewayDatabase) SetImage(v string) {
	o.Image = &v
}

// GetExternalSecretRef returns the ExternalSecretRef field value if set, zero value otherwise.
func (o *GatewayDatabase) GetExternalSecretRef() string {
	if o == nil || IsNil(o.ExternalSecretRef) {
		var ret string
		return ret
	}
	return *o.ExternalSecretRef
}

// GetExternalSecretRefOk returns a tuple with the ExternalSecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayDatabase) GetExternalSecretRefOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSecretRef) {
		return nil, false
	}
	return o.ExternalSecretRef, true
}

// HasExternalSecretRef returns a boolean if a field has been set.
func (o *GatewayDatabase) HasExternalSecretRef() bool {
	if o != nil && !IsNil(o.ExternalSecretRef) {
		return true
	}

	return false
}

// SetExternalSecretRef gets a reference to the given string and assigns it to the ExternalSecretRef field.
func (o *GatewayDatabase) SetExternalSecretRef(v string) {
	o.ExternalSecretRef = &v
}

func (o GatewayDatabase) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayDatabase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.StorageSize) {
		toSerialize["storage_size"] = o.StorageSize
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.ExternalSecretRef) {
		toSerialize["external_secret_ref"] = o.ExternalSecretRef
	}
	return toSerialize, nil
}

func (o *GatewayDatabase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayDatabase := _GatewayDatabase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayDatabase)

	if err != nil {
		return err
	}

	*o = GatewayDatabase(varGatewayDatabase)

	return err
}

type NullableGatewayDatabase struct {
	value *GatewayDatabase
	isSet bool
}

func (v NullableGatewayDatabase) Get() *GatewayDatabase {
	return v.value
}

func (v *NullableGatewayDatabase) Set(val *GatewayDatabase) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayDatabase) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayDatabase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayDatabase(val *GatewayDatabase) *NullableGatewayDatabase {
	return &NullableGatewayDatabase{value: val, isSet: true}
}

func (v NullableGatewayDatabase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayDatabase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
