/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApplicationSyncRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationSyncRequest{}

// ApplicationSyncRequest struct for ApplicationSyncRequest
type ApplicationSyncRequest struct {
	// Override auto_prune for this sync only
	Prune *bool `json:"prune,omitempty"`
	// Override source_target_revision for this sync only
	Revision *string `json:"revision,omitempty"`
	// Required alongside prune to allow project deletion
	PruneProject *bool `json:"prune_project,omitempty"`
}

// NewApplicationSyncRequest instantiates a new ApplicationSyncRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationSyncRequest() *ApplicationSyncRequest {
	this := ApplicationSyncRequest{}
	return &this
}

// NewApplicationSyncRequestWithDefaults instantiates a new ApplicationSyncRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationSyncRequestWithDefaults() *ApplicationSyncRequest {
	this := ApplicationSyncRequest{}
	return &this
}

// GetPrune returns the Prune field value if set, zero value otherwise.
func (o *ApplicationSyncRequest) GetPrune() bool {
	if o == nil || IsNil(o.Prune) {
		var ret bool
		return ret
	}
	return *o.Prune
}

// GetPruneOk returns a tuple with the Prune field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationSyncRequest) GetPruneOk() (*bool, bool) {
	if o == nil || IsNil(o.Prune) {
		return nil, false
	}
	return o.Prune, true
}

// HasPrune returns a boolean if a field has been set.
func (o *ApplicationSyncRequest) HasPrune() bool {
	if o != nil && !IsNil(o.Prune) {
		return true
	}

	return false
}

// SetPrune gets a reference to the given bool and assigns it to the Prune field.
func (o *ApplicationSyncRequest) SetPrune(v bool) {
	o.Prune = &v
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *ApplicationSyncRequest) GetRevision() string {
	if o == nil || IsNil(o.Revision) {
		var ret string
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationSyncRequest) GetRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *ApplicationSyncRequest) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given string and assigns it to the Revision field.
func (o *ApplicationSyncRequest) SetRevision(v string) {
	o.Revision = &v
}

// GetPruneProject returns the PruneProject field value if set, zero value otherwise.
func (o *ApplicationSyncRequest) GetPruneProject() bool {
	if o == nil || IsNil(o.PruneProject) {
		var ret bool
		return ret
	}
	return *o.PruneProject
}

// GetPruneProjectOk returns a tuple with the PruneProject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationSyncRequest) GetPruneProjectOk() (*bool, bool) {
	if o == nil || IsNil(o.PruneProject) {
		return nil, false
	}
	return o.PruneProject, true
}

// HasPruneProject returns a boolean if a field has been set.
func (o *ApplicationSyncRequest) HasPruneProject() bool {
	if o != nil && !IsNil(o.PruneProject) {
		return true
	}

	return false
}

// SetPruneProject gets a reference to the given bool and assigns it to the PruneProject field.
func (o *ApplicationSyncRequest) SetPruneProject(v bool) {
	o.PruneProject = &v
}

func (o ApplicationSyncRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationSyncRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prune) {
		toSerialize["prune"] = o.Prune
	}
	if !IsNil(o.Revision) {
		toSerialize["revision"] = o.Revision
	}
	if !IsNil(o.PruneProject) {
		toSerialize["prune_project"] = o.PruneProject
	}
	return toSerialize, nil
}

type NullableApplicationSyncRequest struct {
	value *ApplicationSyncRequest
	isSet bool
}

func (v NullableApplicationSyncRequest) Get() *ApplicationSyncRequest {
	return v.value
}

func (v *NullableApplicationSyncRequest) Set(val *ApplicationSyncRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationSyncRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationSyncRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationSyncRequest(val *ApplicationSyncRequest) *NullableApplicationSyncRequest {
	return &NullableApplicationSyncRequest{value: val, isSet: true}
}

func (v NullableApplicationSyncRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationSyncRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
