/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Application type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Application{}

// Application struct for Application
type Application struct {
	Id        *string    `json:"id,omitempty"`
	Kind      *string    `json:"kind,omitempty"`
	Href      *string    `json:"href,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Unique human-readable name for this application
	Name string `json:"name"`
	// Git repository URL (HTTPS or SSH)
	SourceRepoUrl string `json:"source_repo_url"`
	// Branch name, tag, or commit SHA (default main)
	SourceTargetRevision *string `json:"source_target_revision,omitempty"`
	// Path within repo to kustomize directory
	SourcePath string `json:"source_path"`
	// Target Ambient API URL; null means local
	DestinationAmbientUrl *string `json:"destination_ambient_url,omitempty"`
	// Target project name
	DestinationProject string `json:"destination_project"`
	// FK to Credential for remote Ambient auth
	CredentialId *string `json:"credential_id,omitempty"`
	// Enable automated sync on git change
	AutoSync *bool `json:"auto_sync,omitempty"`
	// Delete resources removed from git
	AutoPrune *bool `json:"auto_prune,omitempty"`
	// Re-sync when live state drifts
	SelfHeal *bool `json:"self_heal,omitempty"`
	// Comma-separated options: CreateProject=true
	SyncOptions *string `json:"sync_options,omitempty"`
	// Max sync retries on failure (default 3)
	RetryLimit *int32 `json:"retry_limit,omitempty"`
	// Synced | OutOfSync | Unknown
	SyncStatus *string `json:"sync_status,omitempty"`
	// Healthy | Degraded | Progressing | Unknown
	HealthStatus *string `json:"health_status,omitempty"`
	// Last successfully synced git commit SHA
	SyncRevision *string `json:"sync_revision,omitempty"`
	// Succeeded | Failed | Running
	OperationPhase *string `json:"operation_phase,omitempty"`
	// Human-readable sync result summary
	OperationMessage *string `json:"operation_message,omitempty"`
	// JSON array of per-resource sync results
	ResourceStatus *string `json:"resource_status,omitempty"`
	// JSON array of error conditions
	Conditions   *string    `json:"conditions,omitempty"`
	Labels       *string    `json:"labels,omitempty"`
	Annotations  *string    `json:"annotations,omitempty"`
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
}

type _Application Application

// NewApplication instantiates a new Application object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplication(name string, sourceRepoUrl string, sourcePath string, destinationProject string) *Application {
	this := Application{}
	this.Name = name
	this.SourceRepoUrl = sourceRepoUrl
	this.SourcePath = sourcePath
	this.DestinationProject = destinationProject
	return &this
}

// NewApplicationWithDefaults instantiates a new Application object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationWithDefaults() *Application {
	this := Application{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Application) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Application) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Application) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Application) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Application) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *Application) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Application) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Application) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Application) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Application) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Application) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Application) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Application) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Application) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Application) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetName returns the Name field value
func (o *Application) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Application) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Application) SetName(v string) {
	o.Name = v
}

// GetSourceRepoUrl returns the SourceRepoUrl field value
func (o *Application) GetSourceRepoUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceRepoUrl
}

// GetSourceRepoUrlOk returns a tuple with the SourceRepoUrl field value
// and a boolean to check if the value has been set.
func (o *Application) GetSourceRepoUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceRepoUrl, true
}

// SetSourceRepoUrl sets field value
func (o *Application) SetSourceRepoUrl(v string) {
	o.SourceRepoUrl = v
}

// GetSourceTargetRevision returns the SourceTargetRevision field value if set, zero value otherwise.
func (o *Application) GetSourceTargetRevision() string {
	if o == nil || IsNil(o.SourceTargetRevision) {
		var ret string
		return ret
	}
	return *o.SourceTargetRevision
}

// GetSourceTargetRevisionOk returns a tuple with the SourceTargetRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetSourceTargetRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.SourceTargetRevision) {
		return nil, false
	}
	return o.SourceTargetRevision, true
}

// HasSourceTargetRevision returns a boolean if a field has been set.
func (o *Application) HasSourceTargetRevision() bool {
	if o != nil && !IsNil(o.SourceTargetRevision) {
		return true
	}

	return false
}

// SetSourceTargetRevision gets a reference to the given string and assigns it to the SourceTargetRevision field.
func (o *Application) SetSourceTargetRevision(v string) {
	o.SourceTargetRevision = &v
}

// GetSourcePath returns the SourcePath field value
func (o *Application) GetSourcePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourcePath
}

// GetSourcePathOk returns a tuple with the SourcePath field value
// and a boolean to check if the value has been set.
func (o *Application) GetSourcePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourcePath, true
}

// SetSourcePath sets field value
func (o *Application) SetSourcePath(v string) {
	o.SourcePath = v
}

// GetDestinationAmbientUrl returns the DestinationAmbientUrl field value if set, zero value otherwise.
func (o *Application) GetDestinationAmbientUrl() string {
	if o == nil || IsNil(o.DestinationAmbientUrl) {
		var ret string
		return ret
	}
	return *o.DestinationAmbientUrl
}

// GetDestinationAmbientUrlOk returns a tuple with the DestinationAmbientUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetDestinationAmbientUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DestinationAmbientUrl) {
		return nil, false
	}
	return o.DestinationAmbientUrl, true
}

// HasDestinationAmbientUrl returns a boolean if a field has been set.
func (o *Application) HasDestinationAmbientUrl() bool {
	if o != nil && !IsNil(o.DestinationAmbientUrl) {
		return true
	}

	return false
}

// SetDestinationAmbientUrl gets a reference to the given string and assigns it to the DestinationAmbientUrl field.
func (o *Application) SetDestinationAmbientUrl(v string) {
	o.DestinationAmbientUrl = &v
}

// GetDestinationProject returns the DestinationProject field value
func (o *Application) GetDestinationProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationProject
}

// GetDestinationProjectOk returns a tuple with the DestinationProject field value
// and a boolean to check if the value has been set.
func (o *Application) GetDestinationProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationProject, true
}

// SetDestinationProject sets field value
func (o *Application) SetDestinationProject(v string) {
	o.DestinationProject = v
}

// GetCredentialId returns the CredentialId field value if set, zero value otherwise.
func (o *Application) GetCredentialId() string {
	if o == nil || IsNil(o.CredentialId) {
		var ret string
		return ret
	}
	return *o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialId) {
		return nil, false
	}
	return o.CredentialId, true
}

// HasCredentialId returns a boolean if a field has been set.
func (o *Application) HasCredentialId() bool {
	if o != nil && !IsNil(o.CredentialId) {
		return true
	}

	return false
}

// SetCredentialId gets a reference to the given string and assigns it to the CredentialId field.
func (o *Application) SetCredentialId(v string) {
	o.CredentialId = &v
}

// GetAutoSync returns the AutoSync field value if set, zero value otherwise.
func (o *Application) GetAutoSync() bool {
	if o == nil || IsNil(o.AutoSync) {
		var ret bool
		return ret
	}
	return *o.AutoSync
}

// GetAutoSyncOk returns a tuple with the AutoSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetAutoSyncOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoSync) {
		return nil, false
	}
	return o.AutoSync, true
}

// HasAutoSync returns a boolean if a field has been set.
func (o *Application) HasAutoSync() bool {
	if o != nil && !IsNil(o.AutoSync) {
		return true
	}

	return false
}

// SetAutoSync gets a reference to the given bool and assigns it to the AutoSync field.
func (o *Application) SetAutoSync(v bool) {
	o.AutoSync = &v
}

// GetAutoPrune returns the AutoPrune field value if set, zero value otherwise.
func (o *Application) GetAutoPrune() bool {
	if o == nil || IsNil(o.AutoPrune) {
		var ret bool
		return ret
	}
	return *o.AutoPrune
}

// GetAutoPruneOk returns a tuple with the AutoPrune field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetAutoPruneOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoPrune) {
		return nil, false
	}
	return o.AutoPrune, true
}

// HasAutoPrune returns a boolean if a field has been set.
func (o *Application) HasAutoPrune() bool {
	if o != nil && !IsNil(o.AutoPrune) {
		return true
	}

	return false
}

// SetAutoPrune gets a reference to the given bool and assigns it to the AutoPrune field.
func (o *Application) SetAutoPrune(v bool) {
	o.AutoPrune = &v
}

// GetSelfHeal returns the SelfHeal field value if set, zero value otherwise.
func (o *Application) GetSelfHeal() bool {
	if o == nil || IsNil(o.SelfHeal) {
		var ret bool
		return ret
	}
	return *o.SelfHeal
}

// GetSelfHealOk returns a tuple with the SelfHeal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetSelfHealOk() (*bool, bool) {
	if o == nil || IsNil(o.SelfHeal) {
		return nil, false
	}
	return o.SelfHeal, true
}

// HasSelfHeal returns a boolean if a field has been set.
func (o *Application) HasSelfHeal() bool {
	if o != nil && !IsNil(o.SelfHeal) {
		return true
	}

	return false
}

// SetSelfHeal gets a reference to the given bool and assigns it to the SelfHeal field.
func (o *Application) SetSelfHeal(v bool) {
	o.SelfHeal = &v
}

// GetSyncOptions returns the SyncOptions field value if set, zero value otherwise.
func (o *Application) GetSyncOptions() string {
	if o == nil || IsNil(o.SyncOptions) {
		var ret string
		return ret
	}
	return *o.SyncOptions
}

// GetSyncOptionsOk returns a tuple with the SyncOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetSyncOptionsOk() (*string, bool) {
	if o == nil || IsNil(o.SyncOptions) {
		return nil, false
	}
	return o.SyncOptions, true
}

// HasSyncOptions returns a boolean if a field has been set.
func (o *Application) HasSyncOptions() bool {
	if o != nil && !IsNil(o.SyncOptions) {
		return true
	}

	return false
}

// SetSyncOptions gets a reference to the given string and assigns it to the SyncOptions field.
func (o *Application) SetSyncOptions(v string) {
	o.SyncOptions = &v
}

// GetRetryLimit returns the RetryLimit field value if set, zero value otherwise.
func (o *Application) GetRetryLimit() int32 {
	if o == nil || IsNil(o.RetryLimit) {
		var ret int32
		return ret
	}
	return *o.RetryLimit
}

// GetRetryLimitOk returns a tuple with the RetryLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetRetryLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryLimit) {
		return nil, false
	}
	return o.RetryLimit, true
}

// HasRetryLimit returns a boolean if a field has been set.
func (o *Application) HasRetryLimit() bool {
	if o != nil && !IsNil(o.RetryLimit) {
		return true
	}

	return false
}

// SetRetryLimit gets a reference to the given int32 and assigns it to the RetryLimit field.
func (o *Application) SetRetryLimit(v int32) {
	o.RetryLimit = &v
}

// GetSyncStatus returns the SyncStatus field value if set, zero value otherwise.
func (o *Application) GetSyncStatus() string {
	if o == nil || IsNil(o.SyncStatus) {
		var ret string
		return ret
	}
	return *o.SyncStatus
}

// GetSyncStatusOk returns a tuple with the SyncStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetSyncStatusOk() (*string, bool) {
	if o == nil || IsNil(o.SyncStatus) {
		return nil, false
	}
	return o.SyncStatus, true
}

// HasSyncStatus returns a boolean if a field has been set.
func (o *Application) HasSyncStatus() bool {
	if o != nil && !IsNil(o.SyncStatus) {
		return true
	}

	return false
}

// SetSyncStatus gets a reference to the given string and assigns it to the SyncStatus field.
func (o *Application) SetSyncStatus(v string) {
	o.SyncStatus = &v
}

// GetHealthStatus returns the HealthStatus field value if set, zero value otherwise.
func (o *Application) GetHealthStatus() string {
	if o == nil || IsNil(o.HealthStatus) {
		var ret string
		return ret
	}
	return *o.HealthStatus
}

// GetHealthStatusOk returns a tuple with the HealthStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetHealthStatusOk() (*string, bool) {
	if o == nil || IsNil(o.HealthStatus) {
		return nil, false
	}
	return o.HealthStatus, true
}

// HasHealthStatus returns a boolean if a field has been set.
func (o *Application) HasHealthStatus() bool {
	if o != nil && !IsNil(o.HealthStatus) {
		return true
	}

	return false
}

// SetHealthStatus gets a reference to the given string and assigns it to the HealthStatus field.
func (o *Application) SetHealthStatus(v string) {
	o.HealthStatus = &v
}

// GetSyncRevision returns the SyncRevision field value if set, zero value otherwise.
func (o *Application) GetSyncRevision() string {
	if o == nil || IsNil(o.SyncRevision) {
		var ret string
		return ret
	}
	return *o.SyncRevision
}

// GetSyncRevisionOk returns a tuple with the SyncRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetSyncRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.SyncRevision) {
		return nil, false
	}
	return o.SyncRevision, true
}

// HasSyncRevision returns a boolean if a field has been set.
func (o *Application) HasSyncRevision() bool {
	if o != nil && !IsNil(o.SyncRevision) {
		return true
	}

	return false
}

// SetSyncRevision gets a reference to the given string and assigns it to the SyncRevision field.
func (o *Application) SetSyncRevision(v string) {
	o.SyncRevision = &v
}

// GetOperationPhase returns the OperationPhase field value if set, zero value otherwise.
func (o *Application) GetOperationPhase() string {
	if o == nil || IsNil(o.OperationPhase) {
		var ret string
		return ret
	}
	return *o.OperationPhase
}

// GetOperationPhaseOk returns a tuple with the OperationPhase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetOperationPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.OperationPhase) {
		return nil, false
	}
	return o.OperationPhase, true
}

// HasOperationPhase returns a boolean if a field has been set.
func (o *Application) HasOperationPhase() bool {
	if o != nil && !IsNil(o.OperationPhase) {
		return true
	}

	return false
}

// SetOperationPhase gets a reference to the given string and assigns it to the OperationPhase field.
func (o *Application) SetOperationPhase(v string) {
	o.OperationPhase = &v
}

// GetOperationMessage returns the OperationMessage field value if set, zero value otherwise.
func (o *Application) GetOperationMessage() string {
	if o == nil || IsNil(o.OperationMessage) {
		var ret string
		return ret
	}
	return *o.OperationMessage
}

// GetOperationMessageOk returns a tuple with the OperationMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetOperationMessageOk() (*string, bool) {
	if o == nil || IsNil(o.OperationMessage) {
		return nil, false
	}
	return o.OperationMessage, true
}

// HasOperationMessage returns a boolean if a field has been set.
func (o *Application) HasOperationMessage() bool {
	if o != nil && !IsNil(o.OperationMessage) {
		return true
	}

	return false
}

// SetOperationMessage gets a reference to the given string and assigns it to the OperationMessage field.
func (o *Application) SetOperationMessage(v string) {
	o.OperationMessage = &v
}

// GetResourceStatus returns the ResourceStatus field value if set, zero value otherwise.
func (o *Application) GetResourceStatus() string {
	if o == nil || IsNil(o.ResourceStatus) {
		var ret string
		return ret
	}
	return *o.ResourceStatus
}

// GetResourceStatusOk returns a tuple with the ResourceStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetResourceStatusOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceStatus) {
		return nil, false
	}
	return o.ResourceStatus, true
}

// HasResourceStatus returns a boolean if a field has been set.
func (o *Application) HasResourceStatus() bool {
	if o != nil && !IsNil(o.ResourceStatus) {
		return true
	}

	return false
}

// SetResourceStatus gets a reference to the given string and assigns it to the ResourceStatus field.
func (o *Application) SetResourceStatus(v string) {
	o.ResourceStatus = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *Application) GetConditions() string {
	if o == nil || IsNil(o.Conditions) {
		var ret string
		return ret
	}
	return *o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetConditionsOk() (*string, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *Application) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given string and assigns it to the Conditions field.
func (o *Application) SetConditions(v string) {
	o.Conditions = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Application) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Application) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *Application) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *Application) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *Application) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *Application) SetAnnotations(v string) {
	o.Annotations = &v
}

// GetLastSyncedAt returns the LastSyncedAt field value if set, zero value otherwise.
func (o *Application) GetLastSyncedAt() time.Time {
	if o == nil || IsNil(o.LastSyncedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastSyncedAt
}

// GetLastSyncedAtOk returns a tuple with the LastSyncedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetLastSyncedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSyncedAt) {
		return nil, false
	}
	return o.LastSyncedAt, true
}

// HasLastSyncedAt returns a boolean if a field has been set.
func (o *Application) HasLastSyncedAt() bool {
	if o != nil && !IsNil(o.LastSyncedAt) {
		return true
	}

	return false
}

// SetLastSyncedAt gets a reference to the given time.Time and assigns it to the LastSyncedAt field.
func (o *Application) SetLastSyncedAt(v time.Time) {
	o.LastSyncedAt = &v
}

func (o Application) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Application) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["name"] = o.Name
	toSerialize["source_repo_url"] = o.SourceRepoUrl
	if !IsNil(o.SourceTargetRevision) {
		toSerialize["source_target_revision"] = o.SourceTargetRevision
	}
	toSerialize["source_path"] = o.SourcePath
	if !IsNil(o.DestinationAmbientUrl) {
		toSerialize["destination_ambient_url"] = o.DestinationAmbientUrl
	}
	toSerialize["destination_project"] = o.DestinationProject
	if !IsNil(o.CredentialId) {
		toSerialize["credential_id"] = o.CredentialId
	}
	if !IsNil(o.AutoSync) {
		toSerialize["auto_sync"] = o.AutoSync
	}
	if !IsNil(o.AutoPrune) {
		toSerialize["auto_prune"] = o.AutoPrune
	}
	if !IsNil(o.SelfHeal) {
		toSerialize["self_heal"] = o.SelfHeal
	}
	if !IsNil(o.SyncOptions) {
		toSerialize["sync_options"] = o.SyncOptions
	}
	if !IsNil(o.RetryLimit) {
		toSerialize["retry_limit"] = o.RetryLimit
	}
	if !IsNil(o.SyncStatus) {
		toSerialize["sync_status"] = o.SyncStatus
	}
	if !IsNil(o.HealthStatus) {
		toSerialize["health_status"] = o.HealthStatus
	}
	if !IsNil(o.SyncRevision) {
		toSerialize["sync_revision"] = o.SyncRevision
	}
	if !IsNil(o.OperationPhase) {
		toSerialize["operation_phase"] = o.OperationPhase
	}
	if !IsNil(o.OperationMessage) {
		toSerialize["operation_message"] = o.OperationMessage
	}
	if !IsNil(o.ResourceStatus) {
		toSerialize["resource_status"] = o.ResourceStatus
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.LastSyncedAt) {
		toSerialize["last_synced_at"] = o.LastSyncedAt
	}
	return toSerialize, nil
}

func (o *Application) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"source_repo_url",
		"source_path",
		"destination_project",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplication := _Application{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplication)

	if err != nil {
		return err
	}

	*o = Application(varApplication)

	return err
}

type NullableApplication struct {
	value *Application
	isSet bool
}

func (v NullableApplication) Get() *Application {
	return v.value
}

func (v *NullableApplication) Set(val *Application) {
	v.value = val
	v.isSet = true
}

func (v NullableApplication) IsSet() bool {
	return v.isSet
}

func (v *NullableApplication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplication(val *Application) *NullableApplication {
	return &NullableApplication{value: val, isSet: true}
}

func (v NullableApplication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
