/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApplicationPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationPatchRequest{}

// ApplicationPatchRequest struct for ApplicationPatchRequest
type ApplicationPatchRequest struct {
	Name                  *string `json:"name,omitempty"`
	SourceRepoUrl         *string `json:"source_repo_url,omitempty"`
	SourceTargetRevision  *string `json:"source_target_revision,omitempty"`
	SourcePath            *string `json:"source_path,omitempty"`
	DestinationAmbientUrl *string `json:"destination_ambient_url,omitempty"`
	DestinationProject    *string `json:"destination_project,omitempty"`
	CredentialId          *string `json:"credential_id,omitempty"`
	AutoSync              *bool   `json:"auto_sync,omitempty"`
	AutoPrune             *bool   `json:"auto_prune,omitempty"`
	SelfHeal              *bool   `json:"self_heal,omitempty"`
	SyncOptions           *string `json:"sync_options,omitempty"`
	RetryLimit            *int32  `json:"retry_limit,omitempty"`
	Labels                *string `json:"labels,omitempty"`
	Annotations           *string `json:"annotations,omitempty"`
}

// NewApplicationPatchRequest instantiates a new ApplicationPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationPatchRequest() *ApplicationPatchRequest {
	this := ApplicationPatchRequest{}
	return &this
}

// NewApplicationPatchRequestWithDefaults instantiates a new ApplicationPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationPatchRequestWithDefaults() *ApplicationPatchRequest {
	this := ApplicationPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetSourceRepoUrl returns the SourceRepoUrl field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetSourceRepoUrl() string {
	if o == nil || IsNil(o.SourceRepoUrl) {
		var ret string
		return ret
	}
	return *o.SourceRepoUrl
}

// GetSourceRepoUrlOk returns a tuple with the SourceRepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetSourceRepoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SourceRepoUrl) {
		return nil, false
	}
	return o.SourceRepoUrl, true
}

// HasSourceRepoUrl returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasSourceRepoUrl() bool {
	if o != nil && !IsNil(o.SourceRepoUrl) {
		return true
	}

	return false
}

// SetSourceRepoUrl gets a reference to the given string and assigns it to the SourceRepoUrl field.
func (o *ApplicationPatchRequest) SetSourceRepoUrl(v string) {
	o.SourceRepoUrl = &v
}

// GetSourceTargetRevision returns the SourceTargetRevision field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetSourceTargetRevision() string {
	if o == nil || IsNil(o.SourceTargetRevision) {
		var ret string
		return ret
	}
	return *o.SourceTargetRevision
}

// GetSourceTargetRevisionOk returns a tuple with the SourceTargetRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetSourceTargetRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.SourceTargetRevision) {
		return nil, false
	}
	return o.SourceTargetRevision, true
}

// HasSourceTargetRevision returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasSourceTargetRevision() bool {
	if o != nil && !IsNil(o.SourceTargetRevision) {
		return true
	}

	return false
}

// SetSourceTargetRevision gets a reference to the given string and assigns it to the SourceTargetRevision field.
func (o *ApplicationPatchRequest) SetSourceTargetRevision(v string) {
	o.SourceTargetRevision = &v
}

// GetSourcePath returns the SourcePath field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetSourcePath() string {
	if o == nil || IsNil(o.SourcePath) {
		var ret string
		return ret
	}
	return *o.SourcePath
}

// GetSourcePathOk returns a tuple with the SourcePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetSourcePathOk() (*string, bool) {
	if o == nil || IsNil(o.SourcePath) {
		return nil, false
	}
	return o.SourcePath, true
}

// HasSourcePath returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasSourcePath() bool {
	if o != nil && !IsNil(o.SourcePath) {
		return true
	}

	return false
}

// SetSourcePath gets a reference to the given string and assigns it to the SourcePath field.
func (o *ApplicationPatchRequest) SetSourcePath(v string) {
	o.SourcePath = &v
}

// GetDestinationAmbientUrl returns the DestinationAmbientUrl field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetDestinationAmbientUrl() string {
	if o == nil || IsNil(o.DestinationAmbientUrl) {
		var ret string
		return ret
	}
	return *o.DestinationAmbientUrl
}

// GetDestinationAmbientUrlOk returns a tuple with the DestinationAmbientUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetDestinationAmbientUrlOk() (*string, bool) {
	if o == nil || IsNil(o.DestinationAmbientUrl) {
		return nil, false
	}
	return o.DestinationAmbientUrl, true
}

// HasDestinationAmbientUrl returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasDestinationAmbientUrl() bool {
	if o != nil && !IsNil(o.DestinationAmbientUrl) {
		return true
	}

	return false
}

// SetDestinationAmbientUrl gets a reference to the given string and assigns it to the DestinationAmbientUrl field.
func (o *ApplicationPatchRequest) SetDestinationAmbientUrl(v string) {
	o.DestinationAmbientUrl = &v
}

// GetDestinationProject returns the DestinationProject field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetDestinationProject() string {
	if o == nil || IsNil(o.DestinationProject) {
		var ret string
		return ret
	}
	return *o.DestinationProject
}

// GetDestinationProjectOk returns a tuple with the DestinationProject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetDestinationProjectOk() (*string, bool) {
	if o == nil || IsNil(o.DestinationProject) {
		return nil, false
	}
	return o.DestinationProject, true
}

// HasDestinationProject returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasDestinationProject() bool {
	if o != nil && !IsNil(o.DestinationProject) {
		return true
	}

	return false
}

// SetDestinationProject gets a reference to the given string and assigns it to the DestinationProject field.
func (o *ApplicationPatchRequest) SetDestinationProject(v string) {
	o.DestinationProject = &v
}

// GetCredentialId returns the CredentialId field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetCredentialId() string {
	if o == nil || IsNil(o.CredentialId) {
		var ret string
		return ret
	}
	return *o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialId) {
		return nil, false
	}
	return o.CredentialId, true
}

// HasCredentialId returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasCredentialId() bool {
	if o != nil && !IsNil(o.CredentialId) {
		return true
	}

	return false
}

// SetCredentialId gets a reference to the given string and assigns it to the CredentialId field.
func (o *ApplicationPatchRequest) SetCredentialId(v string) {
	o.CredentialId = &v
}

// GetAutoSync returns the AutoSync field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetAutoSync() bool {
	if o == nil || IsNil(o.AutoSync) {
		var ret bool
		return ret
	}
	return *o.AutoSync
}

// GetAutoSyncOk returns a tuple with the AutoSync field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetAutoSyncOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoSync) {
		return nil, false
	}
	return o.AutoSync, true
}

// HasAutoSync returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasAutoSync() bool {
	if o != nil && !IsNil(o.AutoSync) {
		return true
	}

	return false
}

// SetAutoSync gets a reference to the given bool and assigns it to the AutoSync field.
func (o *ApplicationPatchRequest) SetAutoSync(v bool) {
	o.AutoSync = &v
}

// GetAutoPrune returns the AutoPrune field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetAutoPrune() bool {
	if o == nil || IsNil(o.AutoPrune) {
		var ret bool
		return ret
	}
	return *o.AutoPrune
}

// GetAutoPruneOk returns a tuple with the AutoPrune field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetAutoPruneOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoPrune) {
		return nil, false
	}
	return o.AutoPrune, true
}

// HasAutoPrune returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasAutoPrune() bool {
	if o != nil && !IsNil(o.AutoPrune) {
		return true
	}

	return false
}

// SetAutoPrune gets a reference to the given bool and assigns it to the AutoPrune field.
func (o *ApplicationPatchRequest) SetAutoPrune(v bool) {
	o.AutoPrune = &v
}

// GetSelfHeal returns the SelfHeal field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetSelfHeal() bool {
	if o == nil || IsNil(o.SelfHeal) {
		var ret bool
		return ret
	}
	return *o.SelfHeal
}

// GetSelfHealOk returns a tuple with the SelfHeal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetSelfHealOk() (*bool, bool) {
	if o == nil || IsNil(o.SelfHeal) {
		return nil, false
	}
	return o.SelfHeal, true
}

// HasSelfHeal returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasSelfHeal() bool {
	if o != nil && !IsNil(o.SelfHeal) {
		return true
	}

	return false
}

// SetSelfHeal gets a reference to the given bool and assigns it to the SelfHeal field.
func (o *ApplicationPatchRequest) SetSelfHeal(v bool) {
	o.SelfHeal = &v
}

// GetSyncOptions returns the SyncOptions field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetSyncOptions() string {
	if o == nil || IsNil(o.SyncOptions) {
		var ret string
		return ret
	}
	return *o.SyncOptions
}

// GetSyncOptionsOk returns a tuple with the SyncOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetSyncOptionsOk() (*string, bool) {
	if o == nil || IsNil(o.SyncOptions) {
		return nil, false
	}
	return o.SyncOptions, true
}

// HasSyncOptions returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasSyncOptions() bool {
	if o != nil && !IsNil(o.SyncOptions) {
		return true
	}

	return false
}

// SetSyncOptions gets a reference to the given string and assigns it to the SyncOptions field.
func (o *ApplicationPatchRequest) SetSyncOptions(v string) {
	o.SyncOptions = &v
}

// GetRetryLimit returns the RetryLimit field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetRetryLimit() int32 {
	if o == nil || IsNil(o.RetryLimit) {
		var ret int32
		return ret
	}
	return *o.RetryLimit
}

// GetRetryLimitOk returns a tuple with the RetryLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetRetryLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryLimit) {
		return nil, false
	}
	return o.RetryLimit, true
}

// HasRetryLimit returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasRetryLimit() bool {
	if o != nil && !IsNil(o.RetryLimit) {
		return true
	}

	return false
}

// SetRetryLimit gets a reference to the given int32 and assigns it to the RetryLimit field.
func (o *ApplicationPatchRequest) SetRetryLimit(v int32) {
	o.RetryLimit = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *ApplicationPatchRequest) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *ApplicationPatchRequest) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationPatchRequest) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *ApplicationPatchRequest) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *ApplicationPatchRequest) SetAnnotations(v string) {
	o.Annotations = &v
}

func (o ApplicationPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SourceRepoUrl) {
		toSerialize["source_repo_url"] = o.SourceRepoUrl
	}
	if !IsNil(o.SourceTargetRevision) {
		toSerialize["source_target_revision"] = o.SourceTargetRevision
	}
	if !IsNil(o.SourcePath) {
		toSerialize["source_path"] = o.SourcePath
	}
	if !IsNil(o.DestinationAmbientUrl) {
		toSerialize["destination_ambient_url"] = o.DestinationAmbientUrl
	}
	if !IsNil(o.DestinationProject) {
		toSerialize["destination_project"] = o.DestinationProject
	}
	if !IsNil(o.CredentialId) {
		toSerialize["credential_id"] = o.CredentialId
	}
	if !IsNil(o.AutoSync) {
		toSerialize["auto_sync"] = o.AutoSync
	}
	if !IsNil(o.AutoPrune) {
		toSerialize["auto_prune"] = o.AutoPrune
	}
	if !IsNil(o.SelfHeal) {
		toSerialize["self_heal"] = o.SelfHeal
	}
	if !IsNil(o.SyncOptions) {
		toSerialize["sync_options"] = o.SyncOptions
	}
	if !IsNil(o.RetryLimit) {
		toSerialize["retry_limit"] = o.RetryLimit
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	return toSerialize, nil
}

type NullableApplicationPatchRequest struct {
	value *ApplicationPatchRequest
	isSet bool
}

func (v NullableApplicationPatchRequest) Get() *ApplicationPatchRequest {
	return v.value
}

func (v *NullableApplicationPatchRequest) Set(val *ApplicationPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationPatchRequest(val *ApplicationPatchRequest) *NullableApplicationPatchRequest {
	return &NullableApplicationPatchRequest{value: val, isSet: true}
}

func (v NullableApplicationPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
