/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Session type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Session{}

// Session struct for Session
type Session struct {
	Id                  *string    `json:"id,omitempty"`
	Kind                *string    `json:"kind,omitempty"`
	Href                *string    `json:"href,omitempty"`
	CreatedAt           *time.Time `json:"created_at,omitempty"`
	UpdatedAt           *time.Time `json:"updated_at,omitempty"`
	GatewayId           *string    `json:"gateway_id,omitempty"`
	GatewayWorkspace    *string    `json:"gateway_workspace,omitempty"`
	SandboxId           *string    `json:"sandbox_id,omitempty"`
	SandboxName         *string    `json:"sandbox_name,omitempty"`
	RuntimeBackend      *string    `json:"runtime_backend,omitempty"`
	RunnerGeneration    *string    `json:"runner_generation,omitempty"`
	GatewayEndpoint     *string    `json:"gateway_endpoint,omitempty"`
	GatewayCredentialId *string    `json:"gateway_credential_id,omitempty"`
	RuntimeStatus       *string    `json:"runtime_status,omitempty"`
	RuntimeError        *string    `json:"runtime_error,omitempty"`
	RuntimeDeleted      *bool      `json:"runtime_deleted,omitempty"`
	RuntimeVersion      *int64     `json:"runtime_version,omitempty"`
	Name                string     `json:"name"`
	RepoUrl             *string    `json:"repo_url,omitempty"`
	Prompt              *string    `json:"prompt,omitempty"`
	// Set from authentication token. Cannot be set or modified via API.
	CreatedByUserId *string  `json:"created_by_user_id,omitempty"`
	AssignedUserId  *string  `json:"assigned_user_id,omitempty"`
	WorkflowId      *string  `json:"workflow_id,omitempty"`
	Repos           *string  `json:"repos,omitempty"`
	Timeout         *int32   `json:"timeout,omitempty"`
	LlmModel        *string  `json:"llm_model,omitempty"`
	LlmTemperature  *float64 `json:"llm_temperature,omitempty"`
	LlmMaxTokens    *int32   `json:"llm_max_tokens,omitempty"`
	ParentSessionId *string  `json:"parent_session_id,omitempty"`
	// ID of the ScheduledSession that created this session.
	SourceScheduledSessionId *string `json:"source_scheduled_session_id,omitempty"`
	// Whether to stop the session when the run finishes
	StopOnRunFinished *bool `json:"stop_on_run_finished,omitempty"`
	// The cron tick time this session was created for.
	ScheduledFor         *time.Time `json:"scheduled_for,omitempty"`
	BotAccountName       *string    `json:"bot_account_name,omitempty"`
	ResourceOverrides    *string    `json:"resource_overrides,omitempty"`
	EnvironmentVariables *string    `json:"environment_variables,omitempty"`
	Labels               *string    `json:"labels,omitempty"`
	Annotations          *string    `json:"annotations,omitempty"`
	// The Agent that owns this session. Immutable after creation.
	AgentId *string `json:"agent_id,omitempty"`
	// Immutable after creation. Set at creation time only.
	ProjectId          *string    `json:"project_id,omitempty"`
	Phase              *string    `json:"phase,omitempty"`
	StartTime          *time.Time `json:"start_time,omitempty"`
	CompletionTime     *time.Time `json:"completion_time,omitempty"`
	SdkSessionId       *string    `json:"sdk_session_id,omitempty"`
	SdkRestartCount    *int32     `json:"sdk_restart_count,omitempty"`
	Conditions         *string    `json:"conditions,omitempty"`
	ReconciledRepos    *string    `json:"reconciled_repos,omitempty"`
	ReconciledWorkflow *string    `json:"reconciled_workflow,omitempty"`
	KubeCrName         *string    `json:"kube_cr_name,omitempty"`
	KubeCrUid          *string    `json:"kube_cr_uid,omitempty"`
	KubeNamespace      *string    `json:"kube_namespace,omitempty"`
	// Timestamp of the last agent activity (message push) for staleness detection.
	LastActivityAt *time.Time `json:"last_activity_at,omitempty"`
	// JSON array of sandbox log entries; last snapshot before sandbox stop.
	SandboxLogsSnapshot *string `json:"sandbox_logs_snapshot,omitempty"`
	// JSON sandbox policy response; last snapshot before sandbox stop.
	SandboxPolicySnapshot *string `json:"sandbox_policy_snapshot,omitempty"`
}

type _Session Session

// NewSession instantiates a new Session object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSession(name string) *Session {
	this := Session{}
	this.Name = name
	return &this
}

// NewSessionWithDefaults instantiates a new Session object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionWithDefaults() *Session {
	this := Session{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Session) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Session) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Session) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Session) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Session) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *Session) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Session) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Session) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Session) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Session) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Session) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Session) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Session) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Session) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Session) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetGatewayId returns the GatewayId field value if set, zero value otherwise.
func (o *Session) GetGatewayId() string {
	if o == nil || IsNil(o.GatewayId) {
		var ret string
		return ret
	}
	return *o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetGatewayIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayId) {
		return nil, false
	}
	return o.GatewayId, true
}

// HasGatewayId returns a boolean if a field has been set.
func (o *Session) HasGatewayId() bool {
	if o != nil && !IsNil(o.GatewayId) {
		return true
	}

	return false
}

// SetGatewayId gets a reference to the given string and assigns it to the GatewayId field.
func (o *Session) SetGatewayId(v string) {
	o.GatewayId = &v
}

// GetGatewayWorkspace returns the GatewayWorkspace field value if set, zero value otherwise.
func (o *Session) GetGatewayWorkspace() string {
	if o == nil || IsNil(o.GatewayWorkspace) {
		var ret string
		return ret
	}
	return *o.GatewayWorkspace
}

// GetGatewayWorkspaceOk returns a tuple with the GatewayWorkspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetGatewayWorkspaceOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayWorkspace) {
		return nil, false
	}
	return o.GatewayWorkspace, true
}

// HasGatewayWorkspace returns a boolean if a field has been set.
func (o *Session) HasGatewayWorkspace() bool {
	if o != nil && !IsNil(o.GatewayWorkspace) {
		return true
	}

	return false
}

// SetGatewayWorkspace gets a reference to the given string and assigns it to the GatewayWorkspace field.
func (o *Session) SetGatewayWorkspace(v string) {
	o.GatewayWorkspace = &v
}

// GetSandboxId returns the SandboxId field value if set, zero value otherwise.
func (o *Session) GetSandboxId() string {
	if o == nil || IsNil(o.SandboxId) {
		var ret string
		return ret
	}
	return *o.SandboxId
}

// GetSandboxIdOk returns a tuple with the SandboxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetSandboxIdOk() (*string, bool) {
	if o == nil || IsNil(o.SandboxId) {
		return nil, false
	}
	return o.SandboxId, true
}

// HasSandboxId returns a boolean if a field has been set.
func (o *Session) HasSandboxId() bool {
	if o != nil && !IsNil(o.SandboxId) {
		return true
	}

	return false
}

// SetSandboxId gets a reference to the given string and assigns it to the SandboxId field.
func (o *Session) SetSandboxId(v string) {
	o.SandboxId = &v
}

// GetSandboxName returns the SandboxName field value if set, zero value otherwise.
func (o *Session) GetSandboxName() string {
	if o == nil || IsNil(o.SandboxName) {
		var ret string
		return ret
	}
	return *o.SandboxName
}

// GetSandboxNameOk returns a tuple with the SandboxName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetSandboxNameOk() (*string, bool) {
	if o == nil || IsNil(o.SandboxName) {
		return nil, false
	}
	return o.SandboxName, true
}

// HasSandboxName returns a boolean if a field has been set.
func (o *Session) HasSandboxName() bool {
	if o != nil && !IsNil(o.SandboxName) {
		return true
	}

	return false
}

// SetSandboxName gets a reference to the given string and assigns it to the SandboxName field.
func (o *Session) SetSandboxName(v string) {
	o.SandboxName = &v
}

// GetRuntimeBackend returns the RuntimeBackend field value if set, zero value otherwise.
func (o *Session) GetRuntimeBackend() string {
	if o == nil || IsNil(o.RuntimeBackend) {
		var ret string
		return ret
	}
	return *o.RuntimeBackend
}

// GetRuntimeBackendOk returns a tuple with the RuntimeBackend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetRuntimeBackendOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeBackend) {
		return nil, false
	}
	return o.RuntimeBackend, true
}

// HasRuntimeBackend returns a boolean if a field has been set.
func (o *Session) HasRuntimeBackend() bool {
	if o != nil && !IsNil(o.RuntimeBackend) {
		return true
	}

	return false
}

// SetRuntimeBackend gets a reference to the given string and assigns it to the RuntimeBackend field.
func (o *Session) SetRuntimeBackend(v string) {
	o.RuntimeBackend = &v
}

// GetRunnerGeneration returns the RunnerGeneration field value if set, zero value otherwise.
func (o *Session) GetRunnerGeneration() string {
	if o == nil || IsNil(o.RunnerGeneration) {
		var ret string
		return ret
	}
	return *o.RunnerGeneration
}

// GetRunnerGenerationOk returns a tuple with the RunnerGeneration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetRunnerGenerationOk() (*string, bool) {
	if o == nil || IsNil(o.RunnerGeneration) {
		return nil, false
	}
	return o.RunnerGeneration, true
}

// HasRunnerGeneration returns a boolean if a field has been set.
func (o *Session) HasRunnerGeneration() bool {
	if o != nil && !IsNil(o.RunnerGeneration) {
		return true
	}

	return false
}

// SetRunnerGeneration gets a reference to the given string and assigns it to the RunnerGeneration field.
func (o *Session) SetRunnerGeneration(v string) {
	o.RunnerGeneration = &v
}

// GetGatewayEndpoint returns the GatewayEndpoint field value if set, zero value otherwise.
func (o *Session) GetGatewayEndpoint() string {
	if o == nil || IsNil(o.GatewayEndpoint) {
		var ret string
		return ret
	}
	return *o.GatewayEndpoint
}

// GetGatewayEndpointOk returns a tuple with the GatewayEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetGatewayEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayEndpoint) {
		return nil, false
	}
	return o.GatewayEndpoint, true
}

// HasGatewayEndpoint returns a boolean if a field has been set.
func (o *Session) HasGatewayEndpoint() bool {
	if o != nil && !IsNil(o.GatewayEndpoint) {
		return true
	}

	return false
}

// SetGatewayEndpoint gets a reference to the given string and assigns it to the GatewayEndpoint field.
func (o *Session) SetGatewayEndpoint(v string) {
	o.GatewayEndpoint = &v
}

// GetGatewayCredentialId returns the GatewayCredentialId field value if set, zero value otherwise.
func (o *Session) GetGatewayCredentialId() string {
	if o == nil || IsNil(o.GatewayCredentialId) {
		var ret string
		return ret
	}
	return *o.GatewayCredentialId
}

// GetGatewayCredentialIdOk returns a tuple with the GatewayCredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetGatewayCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayCredentialId) {
		return nil, false
	}
	return o.GatewayCredentialId, true
}

// HasGatewayCredentialId returns a boolean if a field has been set.
func (o *Session) HasGatewayCredentialId() bool {
	if o != nil && !IsNil(o.GatewayCredentialId) {
		return true
	}

	return false
}

// SetGatewayCredentialId gets a reference to the given string and assigns it to the GatewayCredentialId field.
func (o *Session) SetGatewayCredentialId(v string) {
	o.GatewayCredentialId = &v
}

// GetRuntimeStatus returns the RuntimeStatus field value if set, zero value otherwise.
func (o *Session) GetRuntimeStatus() string {
	if o == nil || IsNil(o.RuntimeStatus) {
		var ret string
		return ret
	}
	return *o.RuntimeStatus
}

// GetRuntimeStatusOk returns a tuple with the RuntimeStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetRuntimeStatusOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeStatus) {
		return nil, false
	}
	return o.RuntimeStatus, true
}

// HasRuntimeStatus returns a boolean if a field has been set.
func (o *Session) HasRuntimeStatus() bool {
	if o != nil && !IsNil(o.RuntimeStatus) {
		return true
	}

	return false
}

// SetRuntimeStatus gets a reference to the given string and assigns it to the RuntimeStatus field.
func (o *Session) SetRuntimeStatus(v string) {
	o.RuntimeStatus = &v
}

// GetRuntimeError returns the RuntimeError field value if set, zero value otherwise.
func (o *Session) GetRuntimeError() string {
	if o == nil || IsNil(o.RuntimeError) {
		var ret string
		return ret
	}
	return *o.RuntimeError
}

// GetRuntimeErrorOk returns a tuple with the RuntimeError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetRuntimeErrorOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeError) {
		return nil, false
	}
	return o.RuntimeError, true
}

// HasRuntimeError returns a boolean if a field has been set.
func (o *Session) HasRuntimeError() bool {
	if o != nil && !IsNil(o.RuntimeError) {
		return true
	}

	return false
}

// SetRuntimeError gets a reference to the given string and assigns it to the RuntimeError field.
func (o *Session) SetRuntimeError(v string) {
	o.RuntimeError = &v
}

// GetRuntimeDeleted returns the RuntimeDeleted field value if set, zero value otherwise.
func (o *Session) GetRuntimeDeleted() bool {
	if o == nil || IsNil(o.RuntimeDeleted) {
		var ret bool
		return ret
	}
	return *o.RuntimeDeleted
}

// GetRuntimeDeletedOk returns a tuple with the RuntimeDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetRuntimeDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.RuntimeDeleted) {
		return nil, false
	}
	return o.RuntimeDeleted, true
}

// HasRuntimeDeleted returns a boolean if a field has been set.
func (o *Session) HasRuntimeDeleted() bool {
	if o != nil && !IsNil(o.RuntimeDeleted) {
		return true
	}

	return false
}

// SetRuntimeDeleted gets a reference to the given bool and assigns it to the RuntimeDeleted field.
func (o *Session) SetRuntimeDeleted(v bool) {
	o.RuntimeDeleted = &v
}

// GetRuntimeVersion returns the RuntimeVersion field value if set, zero value otherwise.
func (o *Session) GetRuntimeVersion() int64 {
	if o == nil || IsNil(o.RuntimeVersion) {
		var ret int64
		return ret
	}
	return *o.RuntimeVersion
}

// GetRuntimeVersionOk returns a tuple with the RuntimeVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetRuntimeVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.RuntimeVersion) {
		return nil, false
	}
	return o.RuntimeVersion, true
}

// HasRuntimeVersion returns a boolean if a field has been set.
func (o *Session) HasRuntimeVersion() bool {
	if o != nil && !IsNil(o.RuntimeVersion) {
		return true
	}

	return false
}

// SetRuntimeVersion gets a reference to the given int64 and assigns it to the RuntimeVersion field.
func (o *Session) SetRuntimeVersion(v int64) {
	o.RuntimeVersion = &v
}

// GetName returns the Name field value
func (o *Session) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Session) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Session) SetName(v string) {
	o.Name = v
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise.
func (o *Session) GetRepoUrl() string {
	if o == nil || IsNil(o.RepoUrl) {
		var ret string
		return ret
	}
	return *o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetRepoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepoUrl) {
		return nil, false
	}
	return o.RepoUrl, true
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *Session) HasRepoUrl() bool {
	if o != nil && !IsNil(o.RepoUrl) {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given string and assigns it to the RepoUrl field.
func (o *Session) SetRepoUrl(v string) {
	o.RepoUrl = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *Session) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *Session) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *Session) SetPrompt(v string) {
	o.Prompt = &v
}

// GetCreatedByUserId returns the CreatedByUserId field value if set, zero value otherwise.
func (o *Session) GetCreatedByUserId() string {
	if o == nil || IsNil(o.CreatedByUserId) {
		var ret string
		return ret
	}
	return *o.CreatedByUserId
}

// GetCreatedByUserIdOk returns a tuple with the CreatedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetCreatedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedByUserId) {
		return nil, false
	}
	return o.CreatedByUserId, true
}

// HasCreatedByUserId returns a boolean if a field has been set.
func (o *Session) HasCreatedByUserId() bool {
	if o != nil && !IsNil(o.CreatedByUserId) {
		return true
	}

	return false
}

// SetCreatedByUserId gets a reference to the given string and assigns it to the CreatedByUserId field.
func (o *Session) SetCreatedByUserId(v string) {
	o.CreatedByUserId = &v
}

// GetAssignedUserId returns the AssignedUserId field value if set, zero value otherwise.
func (o *Session) GetAssignedUserId() string {
	if o == nil || IsNil(o.AssignedUserId) {
		var ret string
		return ret
	}
	return *o.AssignedUserId
}

// GetAssignedUserIdOk returns a tuple with the AssignedUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetAssignedUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssignedUserId) {
		return nil, false
	}
	return o.AssignedUserId, true
}

// HasAssignedUserId returns a boolean if a field has been set.
func (o *Session) HasAssignedUserId() bool {
	if o != nil && !IsNil(o.AssignedUserId) {
		return true
	}

	return false
}

// SetAssignedUserId gets a reference to the given string and assigns it to the AssignedUserId field.
func (o *Session) SetAssignedUserId(v string) {
	o.AssignedUserId = &v
}

// GetWorkflowId returns the WorkflowId field value if set, zero value otherwise.
func (o *Session) GetWorkflowId() string {
	if o == nil || IsNil(o.WorkflowId) {
		var ret string
		return ret
	}
	return *o.WorkflowId
}

// GetWorkflowIdOk returns a tuple with the WorkflowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetWorkflowIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowId) {
		return nil, false
	}
	return o.WorkflowId, true
}

// HasWorkflowId returns a boolean if a field has been set.
func (o *Session) HasWorkflowId() bool {
	if o != nil && !IsNil(o.WorkflowId) {
		return true
	}

	return false
}

// SetWorkflowId gets a reference to the given string and assigns it to the WorkflowId field.
func (o *Session) SetWorkflowId(v string) {
	o.WorkflowId = &v
}

// GetRepos returns the Repos field value if set, zero value otherwise.
func (o *Session) GetRepos() string {
	if o == nil || IsNil(o.Repos) {
		var ret string
		return ret
	}
	return *o.Repos
}

// GetReposOk returns a tuple with the Repos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetReposOk() (*string, bool) {
	if o == nil || IsNil(o.Repos) {
		return nil, false
	}
	return o.Repos, true
}

// HasRepos returns a boolean if a field has been set.
func (o *Session) HasRepos() bool {
	if o != nil && !IsNil(o.Repos) {
		return true
	}

	return false
}

// SetRepos gets a reference to the given string and assigns it to the Repos field.
func (o *Session) SetRepos(v string) {
	o.Repos = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *Session) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *Session) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *Session) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetLlmModel returns the LlmModel field value if set, zero value otherwise.
func (o *Session) GetLlmModel() string {
	if o == nil || IsNil(o.LlmModel) {
		var ret string
		return ret
	}
	return *o.LlmModel
}

// GetLlmModelOk returns a tuple with the LlmModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetLlmModelOk() (*string, bool) {
	if o == nil || IsNil(o.LlmModel) {
		return nil, false
	}
	return o.LlmModel, true
}

// HasLlmModel returns a boolean if a field has been set.
func (o *Session) HasLlmModel() bool {
	if o != nil && !IsNil(o.LlmModel) {
		return true
	}

	return false
}

// SetLlmModel gets a reference to the given string and assigns it to the LlmModel field.
func (o *Session) SetLlmModel(v string) {
	o.LlmModel = &v
}

// GetLlmTemperature returns the LlmTemperature field value if set, zero value otherwise.
func (o *Session) GetLlmTemperature() float64 {
	if o == nil || IsNil(o.LlmTemperature) {
		var ret float64
		return ret
	}
	return *o.LlmTemperature
}

// GetLlmTemperatureOk returns a tuple with the LlmTemperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetLlmTemperatureOk() (*float64, bool) {
	if o == nil || IsNil(o.LlmTemperature) {
		return nil, false
	}
	return o.LlmTemperature, true
}

// HasLlmTemperature returns a boolean if a field has been set.
func (o *Session) HasLlmTemperature() bool {
	if o != nil && !IsNil(o.LlmTemperature) {
		return true
	}

	return false
}

// SetLlmTemperature gets a reference to the given float64 and assigns it to the LlmTemperature field.
func (o *Session) SetLlmTemperature(v float64) {
	o.LlmTemperature = &v
}

// GetLlmMaxTokens returns the LlmMaxTokens field value if set, zero value otherwise.
func (o *Session) GetLlmMaxTokens() int32 {
	if o == nil || IsNil(o.LlmMaxTokens) {
		var ret int32
		return ret
	}
	return *o.LlmMaxTokens
}

// GetLlmMaxTokensOk returns a tuple with the LlmMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetLlmMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.LlmMaxTokens) {
		return nil, false
	}
	return o.LlmMaxTokens, true
}

// HasLlmMaxTokens returns a boolean if a field has been set.
func (o *Session) HasLlmMaxTokens() bool {
	if o != nil && !IsNil(o.LlmMaxTokens) {
		return true
	}

	return false
}

// SetLlmMaxTokens gets a reference to the given int32 and assigns it to the LlmMaxTokens field.
func (o *Session) SetLlmMaxTokens(v int32) {
	o.LlmMaxTokens = &v
}

// GetParentSessionId returns the ParentSessionId field value if set, zero value otherwise.
func (o *Session) GetParentSessionId() string {
	if o == nil || IsNil(o.ParentSessionId) {
		var ret string
		return ret
	}
	return *o.ParentSessionId
}

// GetParentSessionIdOk returns a tuple with the ParentSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetParentSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentSessionId) {
		return nil, false
	}
	return o.ParentSessionId, true
}

// HasParentSessionId returns a boolean if a field has been set.
func (o *Session) HasParentSessionId() bool {
	if o != nil && !IsNil(o.ParentSessionId) {
		return true
	}

	return false
}

// SetParentSessionId gets a reference to the given string and assigns it to the ParentSessionId field.
func (o *Session) SetParentSessionId(v string) {
	o.ParentSessionId = &v
}

// GetSourceScheduledSessionId returns the SourceScheduledSessionId field value if set, zero value otherwise.
func (o *Session) GetSourceScheduledSessionId() string {
	if o == nil || IsNil(o.SourceScheduledSessionId) {
		var ret string
		return ret
	}
	return *o.SourceScheduledSessionId
}

// GetSourceScheduledSessionIdOk returns a tuple with the SourceScheduledSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetSourceScheduledSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceScheduledSessionId) {
		return nil, false
	}
	return o.SourceScheduledSessionId, true
}

// HasSourceScheduledSessionId returns a boolean if a field has been set.
func (o *Session) HasSourceScheduledSessionId() bool {
	if o != nil && !IsNil(o.SourceScheduledSessionId) {
		return true
	}

	return false
}

// SetSourceScheduledSessionId gets a reference to the given string and assigns it to the SourceScheduledSessionId field.
func (o *Session) SetSourceScheduledSessionId(v string) {
	o.SourceScheduledSessionId = &v
}

// GetStopOnRunFinished returns the StopOnRunFinished field value if set, zero value otherwise.
func (o *Session) GetStopOnRunFinished() bool {
	if o == nil || IsNil(o.StopOnRunFinished) {
		var ret bool
		return ret
	}
	return *o.StopOnRunFinished
}

// GetStopOnRunFinishedOk returns a tuple with the StopOnRunFinished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetStopOnRunFinishedOk() (*bool, bool) {
	if o == nil || IsNil(o.StopOnRunFinished) {
		return nil, false
	}
	return o.StopOnRunFinished, true
}

// HasStopOnRunFinished returns a boolean if a field has been set.
func (o *Session) HasStopOnRunFinished() bool {
	if o != nil && !IsNil(o.StopOnRunFinished) {
		return true
	}

	return false
}

// SetStopOnRunFinished gets a reference to the given bool and assigns it to the StopOnRunFinished field.
func (o *Session) SetStopOnRunFinished(v bool) {
	o.StopOnRunFinished = &v
}

// GetScheduledFor returns the ScheduledFor field value if set, zero value otherwise.
func (o *Session) GetScheduledFor() time.Time {
	if o == nil || IsNil(o.ScheduledFor) {
		var ret time.Time
		return ret
	}
	return *o.ScheduledFor
}

// GetScheduledForOk returns a tuple with the ScheduledFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetScheduledForOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScheduledFor) {
		return nil, false
	}
	return o.ScheduledFor, true
}

// HasScheduledFor returns a boolean if a field has been set.
func (o *Session) HasScheduledFor() bool {
	if o != nil && !IsNil(o.ScheduledFor) {
		return true
	}

	return false
}

// SetScheduledFor gets a reference to the given time.Time and assigns it to the ScheduledFor field.
func (o *Session) SetScheduledFor(v time.Time) {
	o.ScheduledFor = &v
}

// GetBotAccountName returns the BotAccountName field value if set, zero value otherwise.
func (o *Session) GetBotAccountName() string {
	if o == nil || IsNil(o.BotAccountName) {
		var ret string
		return ret
	}
	return *o.BotAccountName
}

// GetBotAccountNameOk returns a tuple with the BotAccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetBotAccountNameOk() (*string, bool) {
	if o == nil || IsNil(o.BotAccountName) {
		return nil, false
	}
	return o.BotAccountName, true
}

// HasBotAccountName returns a boolean if a field has been set.
func (o *Session) HasBotAccountName() bool {
	if o != nil && !IsNil(o.BotAccountName) {
		return true
	}

	return false
}

// SetBotAccountName gets a reference to the given string and assigns it to the BotAccountName field.
func (o *Session) SetBotAccountName(v string) {
	o.BotAccountName = &v
}

// GetResourceOverrides returns the ResourceOverrides field value if set, zero value otherwise.
func (o *Session) GetResourceOverrides() string {
	if o == nil || IsNil(o.ResourceOverrides) {
		var ret string
		return ret
	}
	return *o.ResourceOverrides
}

// GetResourceOverridesOk returns a tuple with the ResourceOverrides field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetResourceOverridesOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceOverrides) {
		return nil, false
	}
	return o.ResourceOverrides, true
}

// HasResourceOverrides returns a boolean if a field has been set.
func (o *Session) HasResourceOverrides() bool {
	if o != nil && !IsNil(o.ResourceOverrides) {
		return true
	}

	return false
}

// SetResourceOverrides gets a reference to the given string and assigns it to the ResourceOverrides field.
func (o *Session) SetResourceOverrides(v string) {
	o.ResourceOverrides = &v
}

// GetEnvironmentVariables returns the EnvironmentVariables field value if set, zero value otherwise.
func (o *Session) GetEnvironmentVariables() string {
	if o == nil || IsNil(o.EnvironmentVariables) {
		var ret string
		return ret
	}
	return *o.EnvironmentVariables
}

// GetEnvironmentVariablesOk returns a tuple with the EnvironmentVariables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetEnvironmentVariablesOk() (*string, bool) {
	if o == nil || IsNil(o.EnvironmentVariables) {
		return nil, false
	}
	return o.EnvironmentVariables, true
}

// HasEnvironmentVariables returns a boolean if a field has been set.
func (o *Session) HasEnvironmentVariables() bool {
	if o != nil && !IsNil(o.EnvironmentVariables) {
		return true
	}

	return false
}

// SetEnvironmentVariables gets a reference to the given string and assigns it to the EnvironmentVariables field.
func (o *Session) SetEnvironmentVariables(v string) {
	o.EnvironmentVariables = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Session) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Session) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *Session) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *Session) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *Session) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *Session) SetAnnotations(v string) {
	o.Annotations = &v
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *Session) GetAgentId() string {
	if o == nil || IsNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *Session) HasAgentId() bool {
	if o != nil && !IsNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *Session) SetAgentId(v string) {
	o.AgentId = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *Session) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *Session) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *Session) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *Session) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *Session) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *Session) SetPhase(v string) {
	o.Phase = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *Session) GetStartTime() time.Time {
	if o == nil || IsNil(o.StartTime) {
		var ret time.Time
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetStartTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *Session) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given time.Time and assigns it to the StartTime field.
func (o *Session) SetStartTime(v time.Time) {
	o.StartTime = &v
}

// GetCompletionTime returns the CompletionTime field value if set, zero value otherwise.
func (o *Session) GetCompletionTime() time.Time {
	if o == nil || IsNil(o.CompletionTime) {
		var ret time.Time
		return ret
	}
	return *o.CompletionTime
}

// GetCompletionTimeOk returns a tuple with the CompletionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetCompletionTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletionTime) {
		return nil, false
	}
	return o.CompletionTime, true
}

// HasCompletionTime returns a boolean if a field has been set.
func (o *Session) HasCompletionTime() bool {
	if o != nil && !IsNil(o.CompletionTime) {
		return true
	}

	return false
}

// SetCompletionTime gets a reference to the given time.Time and assigns it to the CompletionTime field.
func (o *Session) SetCompletionTime(v time.Time) {
	o.CompletionTime = &v
}

// GetSdkSessionId returns the SdkSessionId field value if set, zero value otherwise.
func (o *Session) GetSdkSessionId() string {
	if o == nil || IsNil(o.SdkSessionId) {
		var ret string
		return ret
	}
	return *o.SdkSessionId
}

// GetSdkSessionIdOk returns a tuple with the SdkSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetSdkSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SdkSessionId) {
		return nil, false
	}
	return o.SdkSessionId, true
}

// HasSdkSessionId returns a boolean if a field has been set.
func (o *Session) HasSdkSessionId() bool {
	if o != nil && !IsNil(o.SdkSessionId) {
		return true
	}

	return false
}

// SetSdkSessionId gets a reference to the given string and assigns it to the SdkSessionId field.
func (o *Session) SetSdkSessionId(v string) {
	o.SdkSessionId = &v
}

// GetSdkRestartCount returns the SdkRestartCount field value if set, zero value otherwise.
func (o *Session) GetSdkRestartCount() int32 {
	if o == nil || IsNil(o.SdkRestartCount) {
		var ret int32
		return ret
	}
	return *o.SdkRestartCount
}

// GetSdkRestartCountOk returns a tuple with the SdkRestartCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetSdkRestartCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SdkRestartCount) {
		return nil, false
	}
	return o.SdkRestartCount, true
}

// HasSdkRestartCount returns a boolean if a field has been set.
func (o *Session) HasSdkRestartCount() bool {
	if o != nil && !IsNil(o.SdkRestartCount) {
		return true
	}

	return false
}

// SetSdkRestartCount gets a reference to the given int32 and assigns it to the SdkRestartCount field.
func (o *Session) SetSdkRestartCount(v int32) {
	o.SdkRestartCount = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *Session) GetConditions() string {
	if o == nil || IsNil(o.Conditions) {
		var ret string
		return ret
	}
	return *o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetConditionsOk() (*string, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *Session) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given string and assigns it to the Conditions field.
func (o *Session) SetConditions(v string) {
	o.Conditions = &v
}

// GetReconciledRepos returns the ReconciledRepos field value if set, zero value otherwise.
func (o *Session) GetReconciledRepos() string {
	if o == nil || IsNil(o.ReconciledRepos) {
		var ret string
		return ret
	}
	return *o.ReconciledRepos
}

// GetReconciledReposOk returns a tuple with the ReconciledRepos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetReconciledReposOk() (*string, bool) {
	if o == nil || IsNil(o.ReconciledRepos) {
		return nil, false
	}
	return o.ReconciledRepos, true
}

// HasReconciledRepos returns a boolean if a field has been set.
func (o *Session) HasReconciledRepos() bool {
	if o != nil && !IsNil(o.ReconciledRepos) {
		return true
	}

	return false
}

// SetReconciledRepos gets a reference to the given string and assigns it to the ReconciledRepos field.
func (o *Session) SetReconciledRepos(v string) {
	o.ReconciledRepos = &v
}

// GetReconciledWorkflow returns the ReconciledWorkflow field value if set, zero value otherwise.
func (o *Session) GetReconciledWorkflow() string {
	if o == nil || IsNil(o.ReconciledWorkflow) {
		var ret string
		return ret
	}
	return *o.ReconciledWorkflow
}

// GetReconciledWorkflowOk returns a tuple with the ReconciledWorkflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetReconciledWorkflowOk() (*string, bool) {
	if o == nil || IsNil(o.ReconciledWorkflow) {
		return nil, false
	}
	return o.ReconciledWorkflow, true
}

// HasReconciledWorkflow returns a boolean if a field has been set.
func (o *Session) HasReconciledWorkflow() bool {
	if o != nil && !IsNil(o.ReconciledWorkflow) {
		return true
	}

	return false
}

// SetReconciledWorkflow gets a reference to the given string and assigns it to the ReconciledWorkflow field.
func (o *Session) SetReconciledWorkflow(v string) {
	o.ReconciledWorkflow = &v
}

// GetKubeCrName returns the KubeCrName field value if set, zero value otherwise.
func (o *Session) GetKubeCrName() string {
	if o == nil || IsNil(o.KubeCrName) {
		var ret string
		return ret
	}
	return *o.KubeCrName
}

// GetKubeCrNameOk returns a tuple with the KubeCrName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetKubeCrNameOk() (*string, bool) {
	if o == nil || IsNil(o.KubeCrName) {
		return nil, false
	}
	return o.KubeCrName, true
}

// HasKubeCrName returns a boolean if a field has been set.
func (o *Session) HasKubeCrName() bool {
	if o != nil && !IsNil(o.KubeCrName) {
		return true
	}

	return false
}

// SetKubeCrName gets a reference to the given string and assigns it to the KubeCrName field.
func (o *Session) SetKubeCrName(v string) {
	o.KubeCrName = &v
}

// GetKubeCrUid returns the KubeCrUid field value if set, zero value otherwise.
func (o *Session) GetKubeCrUid() string {
	if o == nil || IsNil(o.KubeCrUid) {
		var ret string
		return ret
	}
	return *o.KubeCrUid
}

// GetKubeCrUidOk returns a tuple with the KubeCrUid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetKubeCrUidOk() (*string, bool) {
	if o == nil || IsNil(o.KubeCrUid) {
		return nil, false
	}
	return o.KubeCrUid, true
}

// HasKubeCrUid returns a boolean if a field has been set.
func (o *Session) HasKubeCrUid() bool {
	if o != nil && !IsNil(o.KubeCrUid) {
		return true
	}

	return false
}

// SetKubeCrUid gets a reference to the given string and assigns it to the KubeCrUid field.
func (o *Session) SetKubeCrUid(v string) {
	o.KubeCrUid = &v
}

// GetKubeNamespace returns the KubeNamespace field value if set, zero value otherwise.
func (o *Session) GetKubeNamespace() string {
	if o == nil || IsNil(o.KubeNamespace) {
		var ret string
		return ret
	}
	return *o.KubeNamespace
}

// GetKubeNamespaceOk returns a tuple with the KubeNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetKubeNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.KubeNamespace) {
		return nil, false
	}
	return o.KubeNamespace, true
}

// HasKubeNamespace returns a boolean if a field has been set.
func (o *Session) HasKubeNamespace() bool {
	if o != nil && !IsNil(o.KubeNamespace) {
		return true
	}

	return false
}

// SetKubeNamespace gets a reference to the given string and assigns it to the KubeNamespace field.
func (o *Session) SetKubeNamespace(v string) {
	o.KubeNamespace = &v
}

// GetLastActivityAt returns the LastActivityAt field value if set, zero value otherwise.
func (o *Session) GetLastActivityAt() time.Time {
	if o == nil || IsNil(o.LastActivityAt) {
		var ret time.Time
		return ret
	}
	return *o.LastActivityAt
}

// GetLastActivityAtOk returns a tuple with the LastActivityAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetLastActivityAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastActivityAt) {
		return nil, false
	}
	return o.LastActivityAt, true
}

// HasLastActivityAt returns a boolean if a field has been set.
func (o *Session) HasLastActivityAt() bool {
	if o != nil && !IsNil(o.LastActivityAt) {
		return true
	}

	return false
}

// SetLastActivityAt gets a reference to the given time.Time and assigns it to the LastActivityAt field.
func (o *Session) SetLastActivityAt(v time.Time) {
	o.LastActivityAt = &v
}

// GetSandboxLogsSnapshot returns the SandboxLogsSnapshot field value if set, zero value otherwise.
func (o *Session) GetSandboxLogsSnapshot() string {
	if o == nil || IsNil(o.SandboxLogsSnapshot) {
		var ret string
		return ret
	}
	return *o.SandboxLogsSnapshot
}

// GetSandboxLogsSnapshotOk returns a tuple with the SandboxLogsSnapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetSandboxLogsSnapshotOk() (*string, bool) {
	if o == nil || IsNil(o.SandboxLogsSnapshot) {
		return nil, false
	}
	return o.SandboxLogsSnapshot, true
}

// HasSandboxLogsSnapshot returns a boolean if a field has been set.
func (o *Session) HasSandboxLogsSnapshot() bool {
	if o != nil && !IsNil(o.SandboxLogsSnapshot) {
		return true
	}

	return false
}

// SetSandboxLogsSnapshot gets a reference to the given string and assigns it to the SandboxLogsSnapshot field.
func (o *Session) SetSandboxLogsSnapshot(v string) {
	o.SandboxLogsSnapshot = &v
}

// GetSandboxPolicySnapshot returns the SandboxPolicySnapshot field value if set, zero value otherwise.
func (o *Session) GetSandboxPolicySnapshot() string {
	if o == nil || IsNil(o.SandboxPolicySnapshot) {
		var ret string
		return ret
	}
	return *o.SandboxPolicySnapshot
}

// GetSandboxPolicySnapshotOk returns a tuple with the SandboxPolicySnapshot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Session) GetSandboxPolicySnapshotOk() (*string, bool) {
	if o == nil || IsNil(o.SandboxPolicySnapshot) {
		return nil, false
	}
	return o.SandboxPolicySnapshot, true
}

// HasSandboxPolicySnapshot returns a boolean if a field has been set.
func (o *Session) HasSandboxPolicySnapshot() bool {
	if o != nil && !IsNil(o.SandboxPolicySnapshot) {
		return true
	}

	return false
}

// SetSandboxPolicySnapshot gets a reference to the given string and assigns it to the SandboxPolicySnapshot field.
func (o *Session) SetSandboxPolicySnapshot(v string) {
	o.SandboxPolicySnapshot = &v
}

func (o Session) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Session) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.GatewayId) {
		toSerialize["gateway_id"] = o.GatewayId
	}
	if !IsNil(o.GatewayWorkspace) {
		toSerialize["gateway_workspace"] = o.GatewayWorkspace
	}
	if !IsNil(o.SandboxId) {
		toSerialize["sandbox_id"] = o.SandboxId
	}
	if !IsNil(o.SandboxName) {
		toSerialize["sandbox_name"] = o.SandboxName
	}
	if !IsNil(o.RuntimeBackend) {
		toSerialize["runtime_backend"] = o.RuntimeBackend
	}
	if !IsNil(o.RunnerGeneration) {
		toSerialize["runner_generation"] = o.RunnerGeneration
	}
	if !IsNil(o.GatewayEndpoint) {
		toSerialize["gateway_endpoint"] = o.GatewayEndpoint
	}
	if !IsNil(o.GatewayCredentialId) {
		toSerialize["gateway_credential_id"] = o.GatewayCredentialId
	}
	if !IsNil(o.RuntimeStatus) {
		toSerialize["runtime_status"] = o.RuntimeStatus
	}
	if !IsNil(o.RuntimeError) {
		toSerialize["runtime_error"] = o.RuntimeError
	}
	if !IsNil(o.RuntimeDeleted) {
		toSerialize["runtime_deleted"] = o.RuntimeDeleted
	}
	if !IsNil(o.RuntimeVersion) {
		toSerialize["runtime_version"] = o.RuntimeVersion
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.RepoUrl) {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.CreatedByUserId) {
		toSerialize["created_by_user_id"] = o.CreatedByUserId
	}
	if !IsNil(o.AssignedUserId) {
		toSerialize["assigned_user_id"] = o.AssignedUserId
	}
	if !IsNil(o.WorkflowId) {
		toSerialize["workflow_id"] = o.WorkflowId
	}
	if !IsNil(o.Repos) {
		toSerialize["repos"] = o.Repos
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.LlmModel) {
		toSerialize["llm_model"] = o.LlmModel
	}
	if !IsNil(o.LlmTemperature) {
		toSerialize["llm_temperature"] = o.LlmTemperature
	}
	if !IsNil(o.LlmMaxTokens) {
		toSerialize["llm_max_tokens"] = o.LlmMaxTokens
	}
	if !IsNil(o.ParentSessionId) {
		toSerialize["parent_session_id"] = o.ParentSessionId
	}
	if !IsNil(o.SourceScheduledSessionId) {
		toSerialize["source_scheduled_session_id"] = o.SourceScheduledSessionId
	}
	if !IsNil(o.StopOnRunFinished) {
		toSerialize["stop_on_run_finished"] = o.StopOnRunFinished
	}
	if !IsNil(o.ScheduledFor) {
		toSerialize["scheduled_for"] = o.ScheduledFor
	}
	if !IsNil(o.BotAccountName) {
		toSerialize["bot_account_name"] = o.BotAccountName
	}
	if !IsNil(o.ResourceOverrides) {
		toSerialize["resource_overrides"] = o.ResourceOverrides
	}
	if !IsNil(o.EnvironmentVariables) {
		toSerialize["environment_variables"] = o.EnvironmentVariables
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.AgentId) {
		toSerialize["agent_id"] = o.AgentId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	if !IsNil(o.CompletionTime) {
		toSerialize["completion_time"] = o.CompletionTime
	}
	if !IsNil(o.SdkSessionId) {
		toSerialize["sdk_session_id"] = o.SdkSessionId
	}
	if !IsNil(o.SdkRestartCount) {
		toSerialize["sdk_restart_count"] = o.SdkRestartCount
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.ReconciledRepos) {
		toSerialize["reconciled_repos"] = o.ReconciledRepos
	}
	if !IsNil(o.ReconciledWorkflow) {
		toSerialize["reconciled_workflow"] = o.ReconciledWorkflow
	}
	if !IsNil(o.KubeCrName) {
		toSerialize["kube_cr_name"] = o.KubeCrName
	}
	if !IsNil(o.KubeCrUid) {
		toSerialize["kube_cr_uid"] = o.KubeCrUid
	}
	if !IsNil(o.KubeNamespace) {
		toSerialize["kube_namespace"] = o.KubeNamespace
	}
	if !IsNil(o.LastActivityAt) {
		toSerialize["last_activity_at"] = o.LastActivityAt
	}
	if !IsNil(o.SandboxLogsSnapshot) {
		toSerialize["sandbox_logs_snapshot"] = o.SandboxLogsSnapshot
	}
	if !IsNil(o.SandboxPolicySnapshot) {
		toSerialize["sandbox_policy_snapshot"] = o.SandboxPolicySnapshot
	}
	return toSerialize, nil
}

func (o *Session) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSession := _Session{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSession)

	if err != nil {
		return err
	}

	*o = Session(varSession)

	return err
}

type NullableSession struct {
	value *Session
	isSet bool
}

func (v NullableSession) Get() *Session {
	return v.value
}

func (v *NullableSession) Set(val *Session) {
	v.value = val
	v.isSet = true
}

func (v NullableSession) IsSet() bool {
	return v.isSet
}

func (v *NullableSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSession(val *Session) *NullableSession {
	return &NullableSession{value: val, isSet: true}
}

func (v NullableSession) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSession) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
