/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ClusterStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterStatusResponse{}

// ClusterStatusResponse struct for ClusterStatusResponse
type ClusterStatusResponse struct {
	Id              *string    `json:"id,omitempty"`
	Status          *string    `json:"status,omitempty"`
	StatusMessage   *string    `json:"status_message,omitempty"`
	Capacity        *string    `json:"capacity,omitempty"`
	LastHeartbeatAt *time.Time `json:"last_heartbeat_at,omitempty"`
}

// NewClusterStatusResponse instantiates a new ClusterStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterStatusResponse() *ClusterStatusResponse {
	this := ClusterStatusResponse{}
	return &this
}

// NewClusterStatusResponseWithDefaults instantiates a new ClusterStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterStatusResponseWithDefaults() *ClusterStatusResponse {
	this := ClusterStatusResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ClusterStatusResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterStatusResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ClusterStatusResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ClusterStatusResponse) SetId(v string) {
	o.Id = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ClusterStatusResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ClusterStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ClusterStatusResponse) SetStatus(v string) {
	o.Status = &v
}

// GetStatusMessage returns the StatusMessage field value if set, zero value otherwise.
func (o *ClusterStatusResponse) GetStatusMessage() string {
	if o == nil || IsNil(o.StatusMessage) {
		var ret string
		return ret
	}
	return *o.StatusMessage
}

// GetStatusMessageOk returns a tuple with the StatusMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterStatusResponse) GetStatusMessageOk() (*string, bool) {
	if o == nil || IsNil(o.StatusMessage) {
		return nil, false
	}
	return o.StatusMessage, true
}

// HasStatusMessage returns a boolean if a field has been set.
func (o *ClusterStatusResponse) HasStatusMessage() bool {
	if o != nil && !IsNil(o.StatusMessage) {
		return true
	}

	return false
}

// SetStatusMessage gets a reference to the given string and assigns it to the StatusMessage field.
func (o *ClusterStatusResponse) SetStatusMessage(v string) {
	o.StatusMessage = &v
}

// GetCapacity returns the Capacity field value if set, zero value otherwise.
func (o *ClusterStatusResponse) GetCapacity() string {
	if o == nil || IsNil(o.Capacity) {
		var ret string
		return ret
	}
	return *o.Capacity
}

// GetCapacityOk returns a tuple with the Capacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterStatusResponse) GetCapacityOk() (*string, bool) {
	if o == nil || IsNil(o.Capacity) {
		return nil, false
	}
	return o.Capacity, true
}

// HasCapacity returns a boolean if a field has been set.
func (o *ClusterStatusResponse) HasCapacity() bool {
	if o != nil && !IsNil(o.Capacity) {
		return true
	}

	return false
}

// SetCapacity gets a reference to the given string and assigns it to the Capacity field.
func (o *ClusterStatusResponse) SetCapacity(v string) {
	o.Capacity = &v
}

// GetLastHeartbeatAt returns the LastHeartbeatAt field value if set, zero value otherwise.
func (o *ClusterStatusResponse) GetLastHeartbeatAt() time.Time {
	if o == nil || IsNil(o.LastHeartbeatAt) {
		var ret time.Time
		return ret
	}
	return *o.LastHeartbeatAt
}

// GetLastHeartbeatAtOk returns a tuple with the LastHeartbeatAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterStatusResponse) GetLastHeartbeatAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastHeartbeatAt) {
		return nil, false
	}
	return o.LastHeartbeatAt, true
}

// HasLastHeartbeatAt returns a boolean if a field has been set.
func (o *ClusterStatusResponse) HasLastHeartbeatAt() bool {
	if o != nil && !IsNil(o.LastHeartbeatAt) {
		return true
	}

	return false
}

// SetLastHeartbeatAt gets a reference to the given time.Time and assigns it to the LastHeartbeatAt field.
func (o *ClusterStatusResponse) SetLastHeartbeatAt(v time.Time) {
	o.LastHeartbeatAt = &v
}

func (o ClusterStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusMessage) {
		toSerialize["status_message"] = o.StatusMessage
	}
	if !IsNil(o.Capacity) {
		toSerialize["capacity"] = o.Capacity
	}
	if !IsNil(o.LastHeartbeatAt) {
		toSerialize["last_heartbeat_at"] = o.LastHeartbeatAt
	}
	return toSerialize, nil
}

type NullableClusterStatusResponse struct {
	value *ClusterStatusResponse
	isSet bool
}

func (v NullableClusterStatusResponse) Get() *ClusterStatusResponse {
	return v.value
}

func (v *NullableClusterStatusResponse) Set(val *ClusterStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterStatusResponse(val *ClusterStatusResponse) *NullableClusterStatusResponse {
	return &NullableClusterStatusResponse{value: val, isSet: true}
}

func (v NullableClusterStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
