/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClusterPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterPatchRequest{}

// ClusterPatchRequest struct for ClusterPatchRequest
type ClusterPatchRequest struct {
	Name         *string `json:"name,omitempty"`
	Description  *string `json:"description,omitempty"`
	ApiServerUrl *string `json:"api_server_url,omitempty"`
	CredentialId *string `json:"credential_id,omitempty"`
	Role         *string `json:"role,omitempty"`
	Labels       *string `json:"labels,omitempty"`
	Annotations  *string `json:"annotations,omitempty"`
}

// NewClusterPatchRequest instantiates a new ClusterPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterPatchRequest() *ClusterPatchRequest {
	this := ClusterPatchRequest{}
	return &this
}

// NewClusterPatchRequestWithDefaults instantiates a new ClusterPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterPatchRequestWithDefaults() *ClusterPatchRequest {
	this := ClusterPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClusterPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClusterPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClusterPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ClusterPatchRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPatchRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ClusterPatchRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ClusterPatchRequest) SetDescription(v string) {
	o.Description = &v
}

// GetApiServerUrl returns the ApiServerUrl field value if set, zero value otherwise.
func (o *ClusterPatchRequest) GetApiServerUrl() string {
	if o == nil || IsNil(o.ApiServerUrl) {
		var ret string
		return ret
	}
	return *o.ApiServerUrl
}

// GetApiServerUrlOk returns a tuple with the ApiServerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPatchRequest) GetApiServerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ApiServerUrl) {
		return nil, false
	}
	return o.ApiServerUrl, true
}

// HasApiServerUrl returns a boolean if a field has been set.
func (o *ClusterPatchRequest) HasApiServerUrl() bool {
	if o != nil && !IsNil(o.ApiServerUrl) {
		return true
	}

	return false
}

// SetApiServerUrl gets a reference to the given string and assigns it to the ApiServerUrl field.
func (o *ClusterPatchRequest) SetApiServerUrl(v string) {
	o.ApiServerUrl = &v
}

// GetCredentialId returns the CredentialId field value if set, zero value otherwise.
func (o *ClusterPatchRequest) GetCredentialId() string {
	if o == nil || IsNil(o.CredentialId) {
		var ret string
		return ret
	}
	return *o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPatchRequest) GetCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialId) {
		return nil, false
	}
	return o.CredentialId, true
}

// HasCredentialId returns a boolean if a field has been set.
func (o *ClusterPatchRequest) HasCredentialId() bool {
	if o != nil && !IsNil(o.CredentialId) {
		return true
	}

	return false
}

// SetCredentialId gets a reference to the given string and assigns it to the CredentialId field.
func (o *ClusterPatchRequest) SetCredentialId(v string) {
	o.CredentialId = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ClusterPatchRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPatchRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ClusterPatchRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *ClusterPatchRequest) SetRole(v string) {
	o.Role = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ClusterPatchRequest) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPatchRequest) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ClusterPatchRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *ClusterPatchRequest) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *ClusterPatchRequest) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterPatchRequest) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *ClusterPatchRequest) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *ClusterPatchRequest) SetAnnotations(v string) {
	o.Annotations = &v
}

func (o ClusterPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ApiServerUrl) {
		toSerialize["api_server_url"] = o.ApiServerUrl
	}
	if !IsNil(o.CredentialId) {
		toSerialize["credential_id"] = o.CredentialId
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	return toSerialize, nil
}

type NullableClusterPatchRequest struct {
	value *ClusterPatchRequest
	isSet bool
}

func (v NullableClusterPatchRequest) Get() *ClusterPatchRequest {
	return v.value
}

func (v *NullableClusterPatchRequest) Set(val *ClusterPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterPatchRequest(val *ClusterPatchRequest) *NullableClusterPatchRequest {
	return &NullableClusterPatchRequest{value: val, isSet: true}
}

func (v NullableClusterPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
