/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Project type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Project{}

// Project struct for Project
type Project struct {
	Id                       *string    `json:"id,omitempty"`
	Kind                     *string    `json:"kind,omitempty"`
	Href                     *string    `json:"href,omitempty"`
	CreatedAt                *time.Time `json:"created_at,omitempty"`
	UpdatedAt                *time.Time `json:"updated_at,omitempty"`
	RuntimeBackend           *string    `json:"runtime_backend,omitempty"`
	GatewayId                *string    `json:"gateway_id,omitempty"`
	GatewayInstanceId        *string    `json:"gateway_instance_id,omitempty"`
	GatewayEndpoint          *string    `json:"gateway_endpoint,omitempty"`
	GatewayStatus            *string    `json:"gateway_status,omitempty"`
	GatewayError             *string    `json:"gateway_error,omitempty"`
	GatewayCredentialId      *string    `json:"gateway_credential_id,omitempty"`
	GatewayAccountId         *string    `json:"gateway_account_id,omitempty"`
	GatewayAccountExpiresAt  *string    `json:"gateway_account_expires_at,omitempty"`
	GatewayExternalReference *string    `json:"gateway_external_reference,omitempty"`
	RuntimeDeleted           *bool      `json:"runtime_deleted,omitempty"`
	RuntimeVersion           *int64     `json:"runtime_version,omitempty"`
	Name                     string     `json:"name"`
	Description              *string    `json:"description,omitempty"`
	Labels                   *string    `json:"labels,omitempty"`
	Annotations              *string    `json:"annotations,omitempty"`
	// Workspace-level context injected into every agent start in this project
	Prompt *string `json:"prompt,omitempty"`
	Status *string `json:"status,omitempty"`
}

type _Project Project

// NewProject instantiates a new Project object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProject(name string) *Project {
	this := Project{}
	this.Name = name
	return &this
}

// NewProjectWithDefaults instantiates a new Project object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectWithDefaults() *Project {
	this := Project{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Project) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Project) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Project) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *Project) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *Project) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *Project) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *Project) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *Project) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *Project) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Project) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Project) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Project) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Project) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Project) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Project) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetRuntimeBackend returns the RuntimeBackend field value if set, zero value otherwise.
func (o *Project) GetRuntimeBackend() string {
	if o == nil || IsNil(o.RuntimeBackend) {
		var ret string
		return ret
	}
	return *o.RuntimeBackend
}

// GetRuntimeBackendOk returns a tuple with the RuntimeBackend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetRuntimeBackendOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeBackend) {
		return nil, false
	}
	return o.RuntimeBackend, true
}

// HasRuntimeBackend returns a boolean if a field has been set.
func (o *Project) HasRuntimeBackend() bool {
	if o != nil && !IsNil(o.RuntimeBackend) {
		return true
	}

	return false
}

// SetRuntimeBackend gets a reference to the given string and assigns it to the RuntimeBackend field.
func (o *Project) SetRuntimeBackend(v string) {
	o.RuntimeBackend = &v
}

// GetGatewayId returns the GatewayId field value if set, zero value otherwise.
func (o *Project) GetGatewayId() string {
	if o == nil || IsNil(o.GatewayId) {
		var ret string
		return ret
	}
	return *o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetGatewayIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayId) {
		return nil, false
	}
	return o.GatewayId, true
}

// HasGatewayId returns a boolean if a field has been set.
func (o *Project) HasGatewayId() bool {
	if o != nil && !IsNil(o.GatewayId) {
		return true
	}

	return false
}

// SetGatewayId gets a reference to the given string and assigns it to the GatewayId field.
func (o *Project) SetGatewayId(v string) {
	o.GatewayId = &v
}

// GetGatewayInstanceId returns the GatewayInstanceId field value if set, zero value otherwise.
func (o *Project) GetGatewayInstanceId() string {
	if o == nil || IsNil(o.GatewayInstanceId) {
		var ret string
		return ret
	}
	return *o.GatewayInstanceId
}

// GetGatewayInstanceIdOk returns a tuple with the GatewayInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetGatewayInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayInstanceId) {
		return nil, false
	}
	return o.GatewayInstanceId, true
}

// HasGatewayInstanceId returns a boolean if a field has been set.
func (o *Project) HasGatewayInstanceId() bool {
	if o != nil && !IsNil(o.GatewayInstanceId) {
		return true
	}

	return false
}

// SetGatewayInstanceId gets a reference to the given string and assigns it to the GatewayInstanceId field.
func (o *Project) SetGatewayInstanceId(v string) {
	o.GatewayInstanceId = &v
}

// GetGatewayEndpoint returns the GatewayEndpoint field value if set, zero value otherwise.
func (o *Project) GetGatewayEndpoint() string {
	if o == nil || IsNil(o.GatewayEndpoint) {
		var ret string
		return ret
	}
	return *o.GatewayEndpoint
}

// GetGatewayEndpointOk returns a tuple with the GatewayEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetGatewayEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayEndpoint) {
		return nil, false
	}
	return o.GatewayEndpoint, true
}

// HasGatewayEndpoint returns a boolean if a field has been set.
func (o *Project) HasGatewayEndpoint() bool {
	if o != nil && !IsNil(o.GatewayEndpoint) {
		return true
	}

	return false
}

// SetGatewayEndpoint gets a reference to the given string and assigns it to the GatewayEndpoint field.
func (o *Project) SetGatewayEndpoint(v string) {
	o.GatewayEndpoint = &v
}

// GetGatewayStatus returns the GatewayStatus field value if set, zero value otherwise.
func (o *Project) GetGatewayStatus() string {
	if o == nil || IsNil(o.GatewayStatus) {
		var ret string
		return ret
	}
	return *o.GatewayStatus
}

// GetGatewayStatusOk returns a tuple with the GatewayStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetGatewayStatusOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayStatus) {
		return nil, false
	}
	return o.GatewayStatus, true
}

// HasGatewayStatus returns a boolean if a field has been set.
func (o *Project) HasGatewayStatus() bool {
	if o != nil && !IsNil(o.GatewayStatus) {
		return true
	}

	return false
}

// SetGatewayStatus gets a reference to the given string and assigns it to the GatewayStatus field.
func (o *Project) SetGatewayStatus(v string) {
	o.GatewayStatus = &v
}

// GetGatewayError returns the GatewayError field value if set, zero value otherwise.
func (o *Project) GetGatewayError() string {
	if o == nil || IsNil(o.GatewayError) {
		var ret string
		return ret
	}
	return *o.GatewayError
}

// GetGatewayErrorOk returns a tuple with the GatewayError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetGatewayErrorOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayError) {
		return nil, false
	}
	return o.GatewayError, true
}

// HasGatewayError returns a boolean if a field has been set.
func (o *Project) HasGatewayError() bool {
	if o != nil && !IsNil(o.GatewayError) {
		return true
	}

	return false
}

// SetGatewayError gets a reference to the given string and assigns it to the GatewayError field.
func (o *Project) SetGatewayError(v string) {
	o.GatewayError = &v
}

// GetGatewayCredentialId returns the GatewayCredentialId field value if set, zero value otherwise.
func (o *Project) GetGatewayCredentialId() string {
	if o == nil || IsNil(o.GatewayCredentialId) {
		var ret string
		return ret
	}
	return *o.GatewayCredentialId
}

// GetGatewayCredentialIdOk returns a tuple with the GatewayCredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetGatewayCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayCredentialId) {
		return nil, false
	}
	return o.GatewayCredentialId, true
}

// HasGatewayCredentialId returns a boolean if a field has been set.
func (o *Project) HasGatewayCredentialId() bool {
	if o != nil && !IsNil(o.GatewayCredentialId) {
		return true
	}

	return false
}

// SetGatewayCredentialId gets a reference to the given string and assigns it to the GatewayCredentialId field.
func (o *Project) SetGatewayCredentialId(v string) {
	o.GatewayCredentialId = &v
}

// GetGatewayAccountId returns the GatewayAccountId field value if set, zero value otherwise.
func (o *Project) GetGatewayAccountId() string {
	if o == nil || IsNil(o.GatewayAccountId) {
		var ret string
		return ret
	}
	return *o.GatewayAccountId
}

// GetGatewayAccountIdOk returns a tuple with the GatewayAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetGatewayAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayAccountId) {
		return nil, false
	}
	return o.GatewayAccountId, true
}

// HasGatewayAccountId returns a boolean if a field has been set.
func (o *Project) HasGatewayAccountId() bool {
	if o != nil && !IsNil(o.GatewayAccountId) {
		return true
	}

	return false
}

// SetGatewayAccountId gets a reference to the given string and assigns it to the GatewayAccountId field.
func (o *Project) SetGatewayAccountId(v string) {
	o.GatewayAccountId = &v
}

// GetGatewayAccountExpiresAt returns the GatewayAccountExpiresAt field value if set, zero value otherwise.
func (o *Project) GetGatewayAccountExpiresAt() string {
	if o == nil || IsNil(o.GatewayAccountExpiresAt) {
		var ret string
		return ret
	}
	return *o.GatewayAccountExpiresAt
}

// GetGatewayAccountExpiresAtOk returns a tuple with the GatewayAccountExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetGatewayAccountExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayAccountExpiresAt) {
		return nil, false
	}
	return o.GatewayAccountExpiresAt, true
}

// HasGatewayAccountExpiresAt returns a boolean if a field has been set.
func (o *Project) HasGatewayAccountExpiresAt() bool {
	if o != nil && !IsNil(o.GatewayAccountExpiresAt) {
		return true
	}

	return false
}

// SetGatewayAccountExpiresAt gets a reference to the given string and assigns it to the GatewayAccountExpiresAt field.
func (o *Project) SetGatewayAccountExpiresAt(v string) {
	o.GatewayAccountExpiresAt = &v
}

// GetGatewayExternalReference returns the GatewayExternalReference field value if set, zero value otherwise.
func (o *Project) GetGatewayExternalReference() string {
	if o == nil || IsNil(o.GatewayExternalReference) {
		var ret string
		return ret
	}
	return *o.GatewayExternalReference
}

// GetGatewayExternalReferenceOk returns a tuple with the GatewayExternalReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetGatewayExternalReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayExternalReference) {
		return nil, false
	}
	return o.GatewayExternalReference, true
}

// HasGatewayExternalReference returns a boolean if a field has been set.
func (o *Project) HasGatewayExternalReference() bool {
	if o != nil && !IsNil(o.GatewayExternalReference) {
		return true
	}

	return false
}

// SetGatewayExternalReference gets a reference to the given string and assigns it to the GatewayExternalReference field.
func (o *Project) SetGatewayExternalReference(v string) {
	o.GatewayExternalReference = &v
}

// GetRuntimeDeleted returns the RuntimeDeleted field value if set, zero value otherwise.
func (o *Project) GetRuntimeDeleted() bool {
	if o == nil || IsNil(o.RuntimeDeleted) {
		var ret bool
		return ret
	}
	return *o.RuntimeDeleted
}

// GetRuntimeDeletedOk returns a tuple with the RuntimeDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetRuntimeDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.RuntimeDeleted) {
		return nil, false
	}
	return o.RuntimeDeleted, true
}

// HasRuntimeDeleted returns a boolean if a field has been set.
func (o *Project) HasRuntimeDeleted() bool {
	if o != nil && !IsNil(o.RuntimeDeleted) {
		return true
	}

	return false
}

// SetRuntimeDeleted gets a reference to the given bool and assigns it to the RuntimeDeleted field.
func (o *Project) SetRuntimeDeleted(v bool) {
	o.RuntimeDeleted = &v
}

// GetRuntimeVersion returns the RuntimeVersion field value if set, zero value otherwise.
func (o *Project) GetRuntimeVersion() int64 {
	if o == nil || IsNil(o.RuntimeVersion) {
		var ret int64
		return ret
	}
	return *o.RuntimeVersion
}

// GetRuntimeVersionOk returns a tuple with the RuntimeVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetRuntimeVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.RuntimeVersion) {
		return nil, false
	}
	return o.RuntimeVersion, true
}

// HasRuntimeVersion returns a boolean if a field has been set.
func (o *Project) HasRuntimeVersion() bool {
	if o != nil && !IsNil(o.RuntimeVersion) {
		return true
	}

	return false
}

// SetRuntimeVersion gets a reference to the given int64 and assigns it to the RuntimeVersion field.
func (o *Project) SetRuntimeVersion(v int64) {
	o.RuntimeVersion = &v
}

// GetName returns the Name field value
func (o *Project) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Project) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Project) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Project) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Project) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Project) SetDescription(v string) {
	o.Description = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Project) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Project) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *Project) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *Project) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *Project) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *Project) SetAnnotations(v string) {
	o.Annotations = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *Project) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *Project) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *Project) SetPrompt(v string) {
	o.Prompt = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Project) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Project) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Project) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Project) SetStatus(v string) {
	o.Status = &v
}

func (o Project) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Project) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.RuntimeBackend) {
		toSerialize["runtime_backend"] = o.RuntimeBackend
	}
	if !IsNil(o.GatewayId) {
		toSerialize["gateway_id"] = o.GatewayId
	}
	if !IsNil(o.GatewayInstanceId) {
		toSerialize["gateway_instance_id"] = o.GatewayInstanceId
	}
	if !IsNil(o.GatewayEndpoint) {
		toSerialize["gateway_endpoint"] = o.GatewayEndpoint
	}
	if !IsNil(o.GatewayStatus) {
		toSerialize["gateway_status"] = o.GatewayStatus
	}
	if !IsNil(o.GatewayError) {
		toSerialize["gateway_error"] = o.GatewayError
	}
	if !IsNil(o.GatewayCredentialId) {
		toSerialize["gateway_credential_id"] = o.GatewayCredentialId
	}
	if !IsNil(o.GatewayAccountId) {
		toSerialize["gateway_account_id"] = o.GatewayAccountId
	}
	if !IsNil(o.GatewayAccountExpiresAt) {
		toSerialize["gateway_account_expires_at"] = o.GatewayAccountExpiresAt
	}
	if !IsNil(o.GatewayExternalReference) {
		toSerialize["gateway_external_reference"] = o.GatewayExternalReference
	}
	if !IsNil(o.RuntimeDeleted) {
		toSerialize["runtime_deleted"] = o.RuntimeDeleted
	}
	if !IsNil(o.RuntimeVersion) {
		toSerialize["runtime_version"] = o.RuntimeVersion
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *Project) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProject := _Project{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProject)

	if err != nil {
		return err
	}

	*o = Project(varProject)

	return err
}

type NullableProject struct {
	value *Project
	isSet bool
}

func (v NullableProject) Get() *Project {
	return v.value
}

func (v *NullableProject) Set(val *Project) {
	v.value = val
	v.isSet = true
}

func (v NullableProject) IsSet() bool {
	return v.isSet
}

func (v *NullableProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProject(val *Project) *NullableProject {
	return &NullableProject{value: val, isSet: true}
}

func (v NullableProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
