/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SessionRuntimePatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionRuntimePatch{}

// SessionRuntimePatch struct for SessionRuntimePatch
type SessionRuntimePatch struct {
	RuntimeVersion      int64      `json:"runtime_version"`
	GatewayId           *string    `json:"gateway_id,omitempty"`
	GatewayWorkspace    *string    `json:"gateway_workspace,omitempty"`
	SandboxId           *string    `json:"sandbox_id,omitempty"`
	SandboxName         *string    `json:"sandbox_name,omitempty"`
	RuntimeBackend      *string    `json:"runtime_backend,omitempty"`
	RunnerGeneration    *string    `json:"runner_generation,omitempty"`
	GatewayEndpoint     *string    `json:"gateway_endpoint,omitempty"`
	GatewayCredentialId *string    `json:"gateway_credential_id,omitempty"`
	RuntimeStatus       *string    `json:"runtime_status,omitempty"`
	RuntimeError        *string    `json:"runtime_error,omitempty"`
	ExpectedPhase       *string    `json:"expected_phase,omitempty"`
	Phase               *string    `json:"phase,omitempty"`
	KubeCrName          *string    `json:"kube_cr_name,omitempty"`
	KubeCrUid           *string    `json:"kube_cr_uid,omitempty"`
	KubeNamespace       *string    `json:"kube_namespace,omitempty"`
	Snapshots           *string    `json:"snapshots,omitempty"`
	SdkSessionId        *string    `json:"sdk_session_id,omitempty"`
	ReconciledRepos     *string    `json:"reconciled_repos,omitempty"`
	ReconciledWorkflow  *string    `json:"reconciled_workflow,omitempty"`
	StartTime           *time.Time `json:"start_time,omitempty"`
	CompletionTime      *time.Time `json:"completion_time,omitempty"`
}

type _SessionRuntimePatch SessionRuntimePatch

// NewSessionRuntimePatch instantiates a new SessionRuntimePatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionRuntimePatch(runtimeVersion int64) *SessionRuntimePatch {
	this := SessionRuntimePatch{}
	this.RuntimeVersion = runtimeVersion
	return &this
}

// NewSessionRuntimePatchWithDefaults instantiates a new SessionRuntimePatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionRuntimePatchWithDefaults() *SessionRuntimePatch {
	this := SessionRuntimePatch{}
	return &this
}

// GetRuntimeVersion returns the RuntimeVersion field value
func (o *SessionRuntimePatch) GetRuntimeVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RuntimeVersion
}

// GetRuntimeVersionOk returns a tuple with the RuntimeVersion field value
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetRuntimeVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RuntimeVersion, true
}

// SetRuntimeVersion sets field value
func (o *SessionRuntimePatch) SetRuntimeVersion(v int64) {
	o.RuntimeVersion = v
}

// GetGatewayId returns the GatewayId field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetGatewayId() string {
	if o == nil || IsNil(o.GatewayId) {
		var ret string
		return ret
	}
	return *o.GatewayId
}

// GetGatewayIdOk returns a tuple with the GatewayId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetGatewayIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayId) {
		return nil, false
	}
	return o.GatewayId, true
}

// HasGatewayId returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasGatewayId() bool {
	if o != nil && !IsNil(o.GatewayId) {
		return true
	}

	return false
}

// SetGatewayId gets a reference to the given string and assigns it to the GatewayId field.
func (o *SessionRuntimePatch) SetGatewayId(v string) {
	o.GatewayId = &v
}

// GetGatewayWorkspace returns the GatewayWorkspace field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetGatewayWorkspace() string {
	if o == nil || IsNil(o.GatewayWorkspace) {
		var ret string
		return ret
	}
	return *o.GatewayWorkspace
}

// GetGatewayWorkspaceOk returns a tuple with the GatewayWorkspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetGatewayWorkspaceOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayWorkspace) {
		return nil, false
	}
	return o.GatewayWorkspace, true
}

// HasGatewayWorkspace returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasGatewayWorkspace() bool {
	if o != nil && !IsNil(o.GatewayWorkspace) {
		return true
	}

	return false
}

// SetGatewayWorkspace gets a reference to the given string and assigns it to the GatewayWorkspace field.
func (o *SessionRuntimePatch) SetGatewayWorkspace(v string) {
	o.GatewayWorkspace = &v
}

// GetSandboxId returns the SandboxId field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetSandboxId() string {
	if o == nil || IsNil(o.SandboxId) {
		var ret string
		return ret
	}
	return *o.SandboxId
}

// GetSandboxIdOk returns a tuple with the SandboxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetSandboxIdOk() (*string, bool) {
	if o == nil || IsNil(o.SandboxId) {
		return nil, false
	}
	return o.SandboxId, true
}

// HasSandboxId returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasSandboxId() bool {
	if o != nil && !IsNil(o.SandboxId) {
		return true
	}

	return false
}

// SetSandboxId gets a reference to the given string and assigns it to the SandboxId field.
func (o *SessionRuntimePatch) SetSandboxId(v string) {
	o.SandboxId = &v
}

// GetSandboxName returns the SandboxName field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetSandboxName() string {
	if o == nil || IsNil(o.SandboxName) {
		var ret string
		return ret
	}
	return *o.SandboxName
}

// GetSandboxNameOk returns a tuple with the SandboxName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetSandboxNameOk() (*string, bool) {
	if o == nil || IsNil(o.SandboxName) {
		return nil, false
	}
	return o.SandboxName, true
}

// HasSandboxName returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasSandboxName() bool {
	if o != nil && !IsNil(o.SandboxName) {
		return true
	}

	return false
}

// SetSandboxName gets a reference to the given string and assigns it to the SandboxName field.
func (o *SessionRuntimePatch) SetSandboxName(v string) {
	o.SandboxName = &v
}

// GetRuntimeBackend returns the RuntimeBackend field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetRuntimeBackend() string {
	if o == nil || IsNil(o.RuntimeBackend) {
		var ret string
		return ret
	}
	return *o.RuntimeBackend
}

// GetRuntimeBackendOk returns a tuple with the RuntimeBackend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetRuntimeBackendOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeBackend) {
		return nil, false
	}
	return o.RuntimeBackend, true
}

// HasRuntimeBackend returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasRuntimeBackend() bool {
	if o != nil && !IsNil(o.RuntimeBackend) {
		return true
	}

	return false
}

// SetRuntimeBackend gets a reference to the given string and assigns it to the RuntimeBackend field.
func (o *SessionRuntimePatch) SetRuntimeBackend(v string) {
	o.RuntimeBackend = &v
}

// GetRunnerGeneration returns the RunnerGeneration field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetRunnerGeneration() string {
	if o == nil || IsNil(o.RunnerGeneration) {
		var ret string
		return ret
	}
	return *o.RunnerGeneration
}

// GetRunnerGenerationOk returns a tuple with the RunnerGeneration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetRunnerGenerationOk() (*string, bool) {
	if o == nil || IsNil(o.RunnerGeneration) {
		return nil, false
	}
	return o.RunnerGeneration, true
}

// HasRunnerGeneration returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasRunnerGeneration() bool {
	if o != nil && !IsNil(o.RunnerGeneration) {
		return true
	}

	return false
}

// SetRunnerGeneration gets a reference to the given string and assigns it to the RunnerGeneration field.
func (o *SessionRuntimePatch) SetRunnerGeneration(v string) {
	o.RunnerGeneration = &v
}

// GetGatewayEndpoint returns the GatewayEndpoint field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetGatewayEndpoint() string {
	if o == nil || IsNil(o.GatewayEndpoint) {
		var ret string
		return ret
	}
	return *o.GatewayEndpoint
}

// GetGatewayEndpointOk returns a tuple with the GatewayEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetGatewayEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayEndpoint) {
		return nil, false
	}
	return o.GatewayEndpoint, true
}

// HasGatewayEndpoint returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasGatewayEndpoint() bool {
	if o != nil && !IsNil(o.GatewayEndpoint) {
		return true
	}

	return false
}

// SetGatewayEndpoint gets a reference to the given string and assigns it to the GatewayEndpoint field.
func (o *SessionRuntimePatch) SetGatewayEndpoint(v string) {
	o.GatewayEndpoint = &v
}

// GetGatewayCredentialId returns the GatewayCredentialId field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetGatewayCredentialId() string {
	if o == nil || IsNil(o.GatewayCredentialId) {
		var ret string
		return ret
	}
	return *o.GatewayCredentialId
}

// GetGatewayCredentialIdOk returns a tuple with the GatewayCredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetGatewayCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayCredentialId) {
		return nil, false
	}
	return o.GatewayCredentialId, true
}

// HasGatewayCredentialId returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasGatewayCredentialId() bool {
	if o != nil && !IsNil(o.GatewayCredentialId) {
		return true
	}

	return false
}

// SetGatewayCredentialId gets a reference to the given string and assigns it to the GatewayCredentialId field.
func (o *SessionRuntimePatch) SetGatewayCredentialId(v string) {
	o.GatewayCredentialId = &v
}

// GetRuntimeStatus returns the RuntimeStatus field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetRuntimeStatus() string {
	if o == nil || IsNil(o.RuntimeStatus) {
		var ret string
		return ret
	}
	return *o.RuntimeStatus
}

// GetRuntimeStatusOk returns a tuple with the RuntimeStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetRuntimeStatusOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeStatus) {
		return nil, false
	}
	return o.RuntimeStatus, true
}

// HasRuntimeStatus returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasRuntimeStatus() bool {
	if o != nil && !IsNil(o.RuntimeStatus) {
		return true
	}

	return false
}

// SetRuntimeStatus gets a reference to the given string and assigns it to the RuntimeStatus field.
func (o *SessionRuntimePatch) SetRuntimeStatus(v string) {
	o.RuntimeStatus = &v
}

// GetRuntimeError returns the RuntimeError field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetRuntimeError() string {
	if o == nil || IsNil(o.RuntimeError) {
		var ret string
		return ret
	}
	return *o.RuntimeError
}

// GetRuntimeErrorOk returns a tuple with the RuntimeError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetRuntimeErrorOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeError) {
		return nil, false
	}
	return o.RuntimeError, true
}

// HasRuntimeError returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasRuntimeError() bool {
	if o != nil && !IsNil(o.RuntimeError) {
		return true
	}

	return false
}

// SetRuntimeError gets a reference to the given string and assigns it to the RuntimeError field.
func (o *SessionRuntimePatch) SetRuntimeError(v string) {
	o.RuntimeError = &v
}

// GetExpectedPhase returns the ExpectedPhase field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetExpectedPhase() string {
	if o == nil || IsNil(o.ExpectedPhase) {
		var ret string
		return ret
	}
	return *o.ExpectedPhase
}

// GetExpectedPhaseOk returns a tuple with the ExpectedPhase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetExpectedPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.ExpectedPhase) {
		return nil, false
	}
	return o.ExpectedPhase, true
}

// HasExpectedPhase returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasExpectedPhase() bool {
	if o != nil && !IsNil(o.ExpectedPhase) {
		return true
	}

	return false
}

// SetExpectedPhase gets a reference to the given string and assigns it to the ExpectedPhase field.
func (o *SessionRuntimePatch) SetExpectedPhase(v string) {
	o.ExpectedPhase = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *SessionRuntimePatch) SetPhase(v string) {
	o.Phase = &v
}

// GetKubeCrName returns the KubeCrName field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetKubeCrName() string {
	if o == nil || IsNil(o.KubeCrName) {
		var ret string
		return ret
	}
	return *o.KubeCrName
}

// GetKubeCrNameOk returns a tuple with the KubeCrName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetKubeCrNameOk() (*string, bool) {
	if o == nil || IsNil(o.KubeCrName) {
		return nil, false
	}
	return o.KubeCrName, true
}

// HasKubeCrName returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasKubeCrName() bool {
	if o != nil && !IsNil(o.KubeCrName) {
		return true
	}

	return false
}

// SetKubeCrName gets a reference to the given string and assigns it to the KubeCrName field.
func (o *SessionRuntimePatch) SetKubeCrName(v string) {
	o.KubeCrName = &v
}

// GetKubeCrUid returns the KubeCrUid field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetKubeCrUid() string {
	if o == nil || IsNil(o.KubeCrUid) {
		var ret string
		return ret
	}
	return *o.KubeCrUid
}

// GetKubeCrUidOk returns a tuple with the KubeCrUid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetKubeCrUidOk() (*string, bool) {
	if o == nil || IsNil(o.KubeCrUid) {
		return nil, false
	}
	return o.KubeCrUid, true
}

// HasKubeCrUid returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasKubeCrUid() bool {
	if o != nil && !IsNil(o.KubeCrUid) {
		return true
	}

	return false
}

// SetKubeCrUid gets a reference to the given string and assigns it to the KubeCrUid field.
func (o *SessionRuntimePatch) SetKubeCrUid(v string) {
	o.KubeCrUid = &v
}

// GetKubeNamespace returns the KubeNamespace field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetKubeNamespace() string {
	if o == nil || IsNil(o.KubeNamespace) {
		var ret string
		return ret
	}
	return *o.KubeNamespace
}

// GetKubeNamespaceOk returns a tuple with the KubeNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetKubeNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.KubeNamespace) {
		return nil, false
	}
	return o.KubeNamespace, true
}

// HasKubeNamespace returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasKubeNamespace() bool {
	if o != nil && !IsNil(o.KubeNamespace) {
		return true
	}

	return false
}

// SetKubeNamespace gets a reference to the given string and assigns it to the KubeNamespace field.
func (o *SessionRuntimePatch) SetKubeNamespace(v string) {
	o.KubeNamespace = &v
}

// GetSnapshots returns the Snapshots field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetSnapshots() string {
	if o == nil || IsNil(o.Snapshots) {
		var ret string
		return ret
	}
	return *o.Snapshots
}

// GetSnapshotsOk returns a tuple with the Snapshots field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetSnapshotsOk() (*string, bool) {
	if o == nil || IsNil(o.Snapshots) {
		return nil, false
	}
	return o.Snapshots, true
}

// HasSnapshots returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasSnapshots() bool {
	if o != nil && !IsNil(o.Snapshots) {
		return true
	}

	return false
}

// SetSnapshots gets a reference to the given string and assigns it to the Snapshots field.
func (o *SessionRuntimePatch) SetSnapshots(v string) {
	o.Snapshots = &v
}

// GetSdkSessionId returns the SdkSessionId field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetSdkSessionId() string {
	if o == nil || IsNil(o.SdkSessionId) {
		var ret string
		return ret
	}
	return *o.SdkSessionId
}

// GetSdkSessionIdOk returns a tuple with the SdkSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetSdkSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SdkSessionId) {
		return nil, false
	}
	return o.SdkSessionId, true
}

// HasSdkSessionId returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasSdkSessionId() bool {
	if o != nil && !IsNil(o.SdkSessionId) {
		return true
	}

	return false
}

// SetSdkSessionId gets a reference to the given string and assigns it to the SdkSessionId field.
func (o *SessionRuntimePatch) SetSdkSessionId(v string) {
	o.SdkSessionId = &v
}

// GetReconciledRepos returns the ReconciledRepos field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetReconciledRepos() string {
	if o == nil || IsNil(o.ReconciledRepos) {
		var ret string
		return ret
	}
	return *o.ReconciledRepos
}

// GetReconciledReposOk returns a tuple with the ReconciledRepos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetReconciledReposOk() (*string, bool) {
	if o == nil || IsNil(o.ReconciledRepos) {
		return nil, false
	}
	return o.ReconciledRepos, true
}

// HasReconciledRepos returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasReconciledRepos() bool {
	if o != nil && !IsNil(o.ReconciledRepos) {
		return true
	}

	return false
}

// SetReconciledRepos gets a reference to the given string and assigns it to the ReconciledRepos field.
func (o *SessionRuntimePatch) SetReconciledRepos(v string) {
	o.ReconciledRepos = &v
}

// GetReconciledWorkflow returns the ReconciledWorkflow field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetReconciledWorkflow() string {
	if o == nil || IsNil(o.ReconciledWorkflow) {
		var ret string
		return ret
	}
	return *o.ReconciledWorkflow
}

// GetReconciledWorkflowOk returns a tuple with the ReconciledWorkflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetReconciledWorkflowOk() (*string, bool) {
	if o == nil || IsNil(o.ReconciledWorkflow) {
		return nil, false
	}
	return o.ReconciledWorkflow, true
}

// HasReconciledWorkflow returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasReconciledWorkflow() bool {
	if o != nil && !IsNil(o.ReconciledWorkflow) {
		return true
	}

	return false
}

// SetReconciledWorkflow gets a reference to the given string and assigns it to the ReconciledWorkflow field.
func (o *SessionRuntimePatch) SetReconciledWorkflow(v string) {
	o.ReconciledWorkflow = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetStartTime() time.Time {
	if o == nil || IsNil(o.StartTime) {
		var ret time.Time
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetStartTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given time.Time and assigns it to the StartTime field.
func (o *SessionRuntimePatch) SetStartTime(v time.Time) {
	o.StartTime = &v
}

// GetCompletionTime returns the CompletionTime field value if set, zero value otherwise.
func (o *SessionRuntimePatch) GetCompletionTime() time.Time {
	if o == nil || IsNil(o.CompletionTime) {
		var ret time.Time
		return ret
	}
	return *o.CompletionTime
}

// GetCompletionTimeOk returns a tuple with the CompletionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionRuntimePatch) GetCompletionTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompletionTime) {
		return nil, false
	}
	return o.CompletionTime, true
}

// HasCompletionTime returns a boolean if a field has been set.
func (o *SessionRuntimePatch) HasCompletionTime() bool {
	if o != nil && !IsNil(o.CompletionTime) {
		return true
	}

	return false
}

// SetCompletionTime gets a reference to the given time.Time and assigns it to the CompletionTime field.
func (o *SessionRuntimePatch) SetCompletionTime(v time.Time) {
	o.CompletionTime = &v
}

func (o SessionRuntimePatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionRuntimePatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["runtime_version"] = o.RuntimeVersion
	if !IsNil(o.GatewayId) {
		toSerialize["gateway_id"] = o.GatewayId
	}
	if !IsNil(o.GatewayWorkspace) {
		toSerialize["gateway_workspace"] = o.GatewayWorkspace
	}
	if !IsNil(o.SandboxId) {
		toSerialize["sandbox_id"] = o.SandboxId
	}
	if !IsNil(o.SandboxName) {
		toSerialize["sandbox_name"] = o.SandboxName
	}
	if !IsNil(o.RuntimeBackend) {
		toSerialize["runtime_backend"] = o.RuntimeBackend
	}
	if !IsNil(o.RunnerGeneration) {
		toSerialize["runner_generation"] = o.RunnerGeneration
	}
	if !IsNil(o.GatewayEndpoint) {
		toSerialize["gateway_endpoint"] = o.GatewayEndpoint
	}
	if !IsNil(o.GatewayCredentialId) {
		toSerialize["gateway_credential_id"] = o.GatewayCredentialId
	}
	if !IsNil(o.RuntimeStatus) {
		toSerialize["runtime_status"] = o.RuntimeStatus
	}
	if !IsNil(o.RuntimeError) {
		toSerialize["runtime_error"] = o.RuntimeError
	}
	if !IsNil(o.ExpectedPhase) {
		toSerialize["expected_phase"] = o.ExpectedPhase
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.KubeCrName) {
		toSerialize["kube_cr_name"] = o.KubeCrName
	}
	if !IsNil(o.KubeCrUid) {
		toSerialize["kube_cr_uid"] = o.KubeCrUid
	}
	if !IsNil(o.KubeNamespace) {
		toSerialize["kube_namespace"] = o.KubeNamespace
	}
	if !IsNil(o.Snapshots) {
		toSerialize["snapshots"] = o.Snapshots
	}
	if !IsNil(o.SdkSessionId) {
		toSerialize["sdk_session_id"] = o.SdkSessionId
	}
	if !IsNil(o.ReconciledRepos) {
		toSerialize["reconciled_repos"] = o.ReconciledRepos
	}
	if !IsNil(o.ReconciledWorkflow) {
		toSerialize["reconciled_workflow"] = o.ReconciledWorkflow
	}
	if !IsNil(o.StartTime) {
		toSerialize["start_time"] = o.StartTime
	}
	if !IsNil(o.CompletionTime) {
		toSerialize["completion_time"] = o.CompletionTime
	}
	return toSerialize, nil
}

func (o *SessionRuntimePatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"runtime_version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionRuntimePatch := _SessionRuntimePatch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionRuntimePatch)

	if err != nil {
		return err
	}

	*o = SessionRuntimePatch(varSessionRuntimePatch)

	return err
}

type NullableSessionRuntimePatch struct {
	value *SessionRuntimePatch
	isSet bool
}

func (v NullableSessionRuntimePatch) Get() *SessionRuntimePatch {
	return v.value
}

func (v *NullableSessionRuntimePatch) Set(val *SessionRuntimePatch) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionRuntimePatch) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionRuntimePatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionRuntimePatch(val *SessionRuntimePatch) *NullableSessionRuntimePatch {
	return &NullableSessionRuntimePatch{value: val, isSet: true}
}

func (v NullableSessionRuntimePatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionRuntimePatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
