#!/usr/bin/env bash
# Stage ai-security-harness skills and slash commands for APM from GitLab.
#
# Upstream is pinned in scripts/ai-security-harness.lock.yaml (committed).
# Sync always checks out resolved_commit exactly — not floating main.
#
# Requires GITLAB_APM_PAT (read_repository), loaded from .env.local by
# scripts/apm-install.sh before this script runs.
#
# Usage:
#   ./scripts/sync-ai-security-harness-skills.sh            # sync pinned commit
#   ./scripts/sync-ai-security-harness-skills.sh --update-pin  # bump pin to tracking_ref tip

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGE="$ROOT/vendor/ai-security-harness"
CACHE="${AI_SECURITY_HARNESS_CACHE:-$ROOT/.cache/ai-security-harness}"
LOCK_FILE="$ROOT/scripts/ai-security-harness.lock.yaml"

read_lock_field() {
  local key="$1"
  sed -n "s/^${key}: *//p" "$LOCK_FILE" | head -1
}

validate_commit_sha() {
  local sha="$1"
  [[ "$sha" =~ ^[0-9a-f]{40}$ ]]
}

validate_repo_url() {
  local url="$1"
  [[ "$url" =~ ^https://gitlab\.cee\.redhat\.com/hybrid-platforms-sec/ai-security-harness\.git$ ]]
}

with_git_auth() {
  GIT_TERMINAL_PROMPT=0 \
  GIT_HTTP_EXTRAHEADER="PRIVATE-TOKEN: ${GITLAB_APM_PAT}" \
    "$@"
}

load_lock() {
  if [[ ! -f "$LOCK_FILE" ]]; then
    echo "[!] Missing lock file: $LOCK_FILE" >&2
    return 1
  fi

  PIN_REPO="$(read_lock_field repository)"
  PIN_REF="$(read_lock_field tracking_ref)"
  PIN_COMMIT="$(read_lock_field resolved_commit)"

  if ! validate_repo_url "$PIN_REPO"; then
    echo "[!] Lock file repository is not the expected ai-security-harness URL." >&2
    return 1
  fi

  PIN_REF="${PIN_REF:-main}"

  if ! validate_commit_sha "$PIN_COMMIT"; then
    echo "[!] Lock file resolved_commit must be a 40-character git SHA." >&2
    return 1
  fi
}

write_lock_commit() {
  local new_commit="$1"
  local tmp
  tmp="$(mktemp)"
  awk -v commit="$new_commit" '
    /^resolved_commit:/ { print "resolved_commit: " commit; next }
    { print }
  ' "$LOCK_FILE" >"$tmp"
  mv "$tmp" "$LOCK_FILE"
}

ensure_checkout() {
  local want_commit="$1"

  if [[ ! -d "$CACHE/.git" ]]; then
    mkdir -p "$(dirname "$CACHE")"
    with_git_auth git clone "$PIN_REPO" "$CACHE"
  fi

  git -C "$CACHE" remote set-url origin "$PIN_REPO"
  with_git_auth git -C "$CACHE" fetch --depth 1 origin "$want_commit"
  git -C "$CACHE" checkout --detach "$want_commit" >/dev/null

  local actual
  actual="$(git -C "$CACHE" rev-parse HEAD)"
  if [[ "$actual" != "$want_commit" ]]; then
    echo "[!] Checkout mismatch: expected $want_commit, got $actual" >&2
    return 1
  fi

  if [[ ! -d "$CACHE/harnessing" ]]; then
    echo "[!] ai-security-harness checkout is missing harnessing/." >&2
    return 1
  fi

  echo "$CACHE"
}

resolve_source() {
  if [[ -z "${GITLAB_APM_PAT:-}" ]]; then
    echo "[!] GITLAB_APM_PAT is required to fetch ai-security-harness from GitLab." >&2
    return 1
  fi

  load_lock
  ensure_checkout "$PIN_COMMIT"
}

update_pin() {
  if [[ -z "${GITLAB_APM_PAT:-}" ]]; then
    echo "[!] GITLAB_APM_PAT is required to update the harness pin." >&2
    return 1
  fi

  load_lock

  if [[ ! -d "$CACHE/.git" ]]; then
    mkdir -p "$(dirname "$CACHE")"
    with_git_auth git clone --branch "$PIN_REF" --depth 1 "$PIN_REPO" "$CACHE"
  else
    git -C "$CACHE" remote set-url origin "$PIN_REPO"
    with_git_auth git -C "$CACHE" fetch --depth 1 origin "$PIN_REF"
  fi

  local new_commit
  new_commit="$(git -C "$CACHE" rev-parse "origin/${PIN_REF}")"
  if ! validate_commit_sha "$new_commit"; then
    echo "[!] Could not resolve tracking ref origin/${PIN_REF} to a commit." >&2
    return 1
  fi

  local old_commit="$PIN_COMMIT"
  write_lock_commit "$new_commit"
  echo "[+] Updated pin: $old_commit -> $new_commit (tracking_ref: $PIN_REF)"
  ensure_checkout "$new_commit" >/dev/null
}

stage_skills() {
  local src="$1"
  rm -rf "$STAGE"
  mkdir -p "$STAGE/skills"
  cp -a "$src/harnessing" "$STAGE/harnessing"

  cat >"$STAGE/plugin.json" <<'EOF'
{
  "name": "ai-security-harness",
  "version": "1.0.0",
  "description": "Staged ai-security-harness skills and commands for APM (generated by sync-ai-security-harness-skills.sh)"
}
EOF

  local skill_dir name
  for skill_dir in "$STAGE/harnessing"/*/; do
    [[ -f "${skill_dir}SKILL.md" ]] || continue
    name="$(basename "$skill_dir")"
    ln -sfn "../harnessing/$name" "$STAGE/skills/$name"
  done

  stage_commands "$src"

  local skill_count command_count
  skill_count="$(find "$STAGE/skills" -mindepth 1 -maxdepth 1 | wc -l | tr -d ' ')"
  command_count="$(find "$STAGE/commands" -mindepth 1 -maxdepth 1 2>/dev/null | wc -l | tr -d ' ')"
  echo "[+] Staged $skill_count skill(s) and $command_count command(s) at vendor/ai-security-harness (commit: $(git -C "$src" rev-parse --short HEAD))"
}

stage_commands() {
  local src="$1"
  local commands_src="$src/.claude/commands"

  if [[ ! -d "$commands_src" ]]; then
    echo "[!] No .claude/commands directory in ai-security-harness source; skipping commands." >&2
    return 0
  fi

  mkdir -p "$STAGE/commands"

  local cmd name target rel
  for cmd in "$commands_src"/*.md; do
    [[ -e "$cmd" ]] || continue
    name="$(basename "$cmd")"

    if [[ -L "$cmd" ]]; then
      target="$(readlink "$cmd")"
      case "$target" in
        ../../harnessing/*)
          rel="${target#../../harnessing/}"
          if [[ "$rel" == *".."* ]]; then
            echo "[!] Rejecting unsafe command symlink target: $target" >&2
            return 1
          fi
          ln -sfn "../harnessing/$rel" "$STAGE/commands/$name"
          ;;
        *)
          cp -L "$cmd" "$STAGE/commands/$name"
          ;;
      esac
    else
      cp -a "$cmd" "$STAGE/commands/$name"
    fi
  done
}

main() {
  local mode="${1:-}"

  if [[ "$mode" == "--update-pin" ]]; then
    update_pin
  else
    if [[ -n "$mode" ]]; then
      echo "[!] Unknown option: $mode" >&2
      echo "Usage: $0 [--update-pin]" >&2
      return 1
    fi
    resolve_source >/dev/null
  fi

  stage_skills "$CACHE"
}

main "$@"
