// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 7b9a4042824e8e603040cf5b3707b6d7f071d37d973d55845d062a010e813ced
// Generated: 2026-07-05T22:39:06Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Application, ApplicationList, ApplicationCreateRequest, ApplicationPatchRequest } from './application';

export class ApplicationAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: ApplicationCreateRequest, opts?: RequestOptions): Promise<Application> {
    return ambientFetch<Application>(this.config, 'POST', '/applications', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Application> {
    return ambientFetch<Application>(this.config, 'GET', `/applications/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ApplicationList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<ApplicationList>(this.config, 'GET', `/applications${qs}`, undefined, opts);
  }
  async update(id: string, patch: ApplicationPatchRequest, opts?: RequestOptions): Promise<Application> {
    return ambientFetch<Application>(this.config, 'PATCH', `/applications/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/applications/${id}`, undefined, opts);
  }

  async refresh(id: string, opts?: RequestOptions): Promise<Application> {
    return ambientFetch<Application>(this.config, 'POST', `/applications/${id}/refresh`, undefined, opts);
  }

  async sync(id: string, opts?: RequestOptions): Promise<Application> {
    return ambientFetch<Application>(this.config, 'POST', `/applications/${id}/sync`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Application> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
