// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9aca8a0a98838cff1bba965fd3df124f91b80ab8059e441f6fff10863ccf6c35
// Generated: 2026-07-15T21:17:57Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Cluster, ClusterList, ClusterCreateRequest, ClusterPatchRequest } from './cluster';

export class ClusterAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: ClusterCreateRequest, opts?: RequestOptions): Promise<Cluster> {
    return ambientFetch<Cluster>(this.config, 'POST', '/clusters', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Cluster> {
    return ambientFetch<Cluster>(this.config, 'GET', `/clusters/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ClusterList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<ClusterList>(this.config, 'GET', `/clusters${qs}`, undefined, opts);
  }
  async update(id: string, patch: ClusterPatchRequest, opts?: RequestOptions): Promise<Cluster> {
    return ambientFetch<Cluster>(this.config, 'PATCH', `/clusters/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/clusters/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Cluster> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
