// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: bb2b5e37868d956ff9f1ee601b52b1fed3e92f03b4e65337eb669d5782b30340
// Generated: 2026-07-20T00:49:42Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Cluster, ClusterList, ClusterCreateRequest, ClusterPatchRequest, ClusterStatusResponse } from './cluster';

export class ClusterAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: ClusterCreateRequest, opts?: RequestOptions): Promise<Cluster> {
    return ambientFetch<Cluster>(this.config, 'POST', '/clusters', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Cluster> {
    return ambientFetch<Cluster>(this.config, 'GET', `/clusters/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ClusterList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<ClusterList>(this.config, 'GET', `/clusters${qs}`, undefined, opts);
  }
  async update(id: string, patch: ClusterPatchRequest, opts?: RequestOptions): Promise<Cluster> {
    return ambientFetch<Cluster>(this.config, 'PATCH', `/clusters/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/clusters/${id}`, undefined, opts);
  }

  async heartbeat(id: string, opts?: RequestOptions): Promise<ClusterStatusResponse> {
    return ambientFetch<ClusterStatusResponse>(this.config, 'POST', `/clusters/${id}/heartbeat`, undefined, opts);
  }

  async status(id: string, opts?: RequestOptions): Promise<ClusterStatusResponse> {
    return ambientFetch<ClusterStatusResponse>(this.config, 'GET', `/clusters/${id}/status`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Cluster> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
