// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: b30f3bd1a45276080577bd8a42c43e8a02968bf73b2042b7324122b25c73e5b1
// Generated: 2026-07-17T21:03:41Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Credential, CredentialList, CredentialCreateRequest, CredentialPatchRequest } from './credential';

export class CredentialAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: CredentialCreateRequest, opts?: RequestOptions): Promise<Credential> {
    return ambientFetch<Credential>(this.config, 'POST', '/credentials', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Credential> {
    return ambientFetch<Credential>(this.config, 'GET', `/credentials/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<CredentialList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<CredentialList>(this.config, 'GET', `/credentials${qs}`, undefined, opts);
  }
  async update(id: string, patch: CredentialPatchRequest, opts?: RequestOptions): Promise<Credential> {
    return ambientFetch<Credential>(this.config, 'PATCH', `/credentials/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/credentials/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Credential> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
