// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 772a5c6db8aff6e70a9674d7875e1dfa54bd8a6dc5060ffd8044989a8c557aca
// Generated: 2026-06-15T15:41:15Z

import type { ObjectReference, ListMeta } from './base';

export type Credential = ObjectReference & {
  annotations: string;
  description: string;
  email: string;
  labels: string;
  name: string;
  provider: string;
  token: string;
  url: string;
};

export type CredentialList = ListMeta & {
  items: Credential[];
};

export type CredentialCreateRequest = {
  annotations?: string;
  description?: string;
  email?: string;
  labels?: string;
  name: string;
  provider: string;
  token?: string;
  url?: string;
};

export type CredentialPatchRequest = {
  annotations?: string;
  description?: string;
  email?: string;
  labels?: string;
  name?: string;
  provider?: string;
  token?: string;
  url?: string;
};

export class CredentialBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  email(value: string): this {
    this.data['email'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  provider(value: string): this {
    this.data['provider'] = value;
    return this;
  }

  token(value: string): this {
    this.data['token'] = value;
    return this;
  }

  url(value: string): this {
    this.data['url'] = value;
    return this;
  }

  build(): CredentialCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['provider']) {
      throw new Error('provider is required');
    }
    return this.data as CredentialCreateRequest;
  }
}

export class CredentialPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  email(value: string): this {
    this.data['email'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  provider(value: string): this {
    this.data['provider'] = value;
    return this;
  }

  token(value: string): this {
    this.data['token'] = value;
    return this;
  }

  url(value: string): this {
    this.data['url'] = value;
    return this;
  }

  build(): CredentialPatchRequest {
    return this.data as CredentialPatchRequest;
  }
}
