// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9aca8a0a98838cff1bba965fd3df124f91b80ab8059e441f6fff10863ccf6c35
// Generated: 2026-07-15T21:17:57Z

import type { ObjectReference, ListMeta } from './base';

export type Gateway = ObjectReference & {
  annotations: string;
  config: string;
  image: string;
  labels: string;
  name: string;
  oidc: Record<string, unknown>;
  project_id: string;
  server_dns_names: string[];
};

export type GatewayList = ListMeta & {
  items: Gateway[];
};

export type GatewayCreateRequest = {
  annotations?: string;
  config?: string;
  image?: string;
  labels?: string;
  name: string;
  oidc?: Record<string, unknown>;
  project_id: string;
  server_dns_names: string[];
};

export type GatewayPatchRequest = {
  annotations?: string;
  config?: string;
  image?: string;
  labels?: string;
  name?: string;
  oidc?: Record<string, unknown>;
  server_dns_names?: string[];
};

export class GatewayBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  config(value: string): this {
    this.data['config'] = value;
    return this;
  }

  image(value: string): this {
    this.data['image'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  oidc(value: Record<string, unknown>): this {
    this.data['oidc'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  serverDnsNames(value: string[]): this {
    this.data['server_dns_names'] = value;
    return this;
  }

  build(): GatewayCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    return this.data as GatewayCreateRequest;
  }
}

export class GatewayPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  config(value: string): this {
    this.data['config'] = value;
    return this;
  }

  image(value: string): this {
    this.data['image'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  oidc(value: Record<string, unknown>): this {
    this.data['oidc'] = value;
    return this;
  }

  serverDnsNames(value: string[]): this {
    this.data['server_dns_names'] = value;
    return this;
  }

  build(): GatewayPatchRequest {
    return this.data as GatewayPatchRequest;
  }
}
