// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 772a5c6db8aff6e70a9674d7875e1dfa54bd8a6dc5060ffd8044989a8c557aca
// Generated: 2026-06-15T15:41:15Z

import type { ObjectReference, ListMeta } from './base';

export type InboxMessage = ObjectReference & {
  agent_id: string;
  body: string;
  from_agent_id: string;
  from_name: string;
  read: boolean;
};

export type InboxMessageList = ListMeta & {
  items: InboxMessage[];
};

export type InboxMessageCreateRequest = {
  agent_id: string;
  body: string;
  from_agent_id?: string;
  from_name?: string;
};

export type InboxMessagePatchRequest = {
  read?: boolean;
};

export class InboxMessageBuilder {
  private data: Record<string, unknown> = {};


  agentId(value: string): this {
    this.data['agent_id'] = value;
    return this;
  }

  body(value: string): this {
    this.data['body'] = value;
    return this;
  }

  fromAgentId(value: string): this {
    this.data['from_agent_id'] = value;
    return this;
  }

  fromName(value: string): this {
    this.data['from_name'] = value;
    return this;
  }

  build(): InboxMessageCreateRequest {
    if (!this.data['agent_id']) {
      throw new Error('agent_id is required');
    }
    if (!this.data['body']) {
      throw new Error('body is required');
    }
    return this.data as InboxMessageCreateRequest;
  }
}

export class InboxMessagePatchBuilder {
  private data: Record<string, unknown> = {};


  read(value: boolean): this {
    this.data['read'] = value;
    return this;
  }

  build(): InboxMessagePatchRequest {
    return this.data as InboxMessagePatchRequest;
  }
}
