// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: f136081d1442aaec8e6d7e6b5db0a10b55f38cda7e3168930bc03e5eec439d17
// Generated: 2026-06-23T20:52:14Z

import type { ObjectReference, ListMeta } from './base';

export type RoleBinding = ObjectReference & {
  agent_id?: string;
  credential_id?: string;
  project_id?: string;
  role_id: string;
  scope: string;
  session_id?: string;
  user_id?: string;
};

export type RoleBindingList = ListMeta & {
  items: RoleBinding[];
};

export type RoleBindingCreateRequest = {
  agent_id?: string;
  credential_id?: string;
  project_id?: string;
  role_id: string;
  scope: string;
  session_id?: string;
  user_id?: string;
};

export type RoleBindingPatchRequest = {
  agent_id?: string;
  credential_id?: string;
  project_id?: string;
  role_id?: string;
  scope?: string;
  session_id?: string;
  user_id?: string;
};

export class RoleBindingBuilder {
  private data: Record<string, unknown> = {};


  agentId(value: string): this {
    this.data['agent_id'] = value;
    return this;
  }

  credentialId(value: string): this {
    this.data['credential_id'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  roleId(value: string): this {
    this.data['role_id'] = value;
    return this;
  }

  scope(value: string): this {
    this.data['scope'] = value;
    return this;
  }

  sessionId(value: string): this {
    this.data['session_id'] = value;
    return this;
  }

  userId(value: string): this {
    this.data['user_id'] = value;
    return this;
  }

  build(): RoleBindingCreateRequest {
    if (!this.data['role_id']) {
      throw new Error('role_id is required');
    }
    if (!this.data['scope']) {
      throw new Error('scope is required');
    }
    return this.data as RoleBindingCreateRequest;
  }
}

export class RoleBindingPatchBuilder {
  private data: Record<string, unknown> = {};


  agentId(value: string): this {
    this.data['agent_id'] = value;
    return this;
  }

  credentialId(value: string): this {
    this.data['credential_id'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  roleId(value: string): this {
    this.data['role_id'] = value;
    return this;
  }

  scope(value: string): this {
    this.data['scope'] = value;
    return this;
  }

  sessionId(value: string): this {
    this.data['session_id'] = value;
    return this;
  }

  userId(value: string): this {
    this.data['user_id'] = value;
    return this;
  }

  build(): RoleBindingPatchRequest {
    return this.data as RoleBindingPatchRequest;
  }
}
