// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: df1013fa7699ed88854f7bae3d501c698c4f6fea04d78eea92f95e595f81ff18
// Generated: 2026-07-19T05:32:21Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Role, RoleList, RoleCreateRequest, RolePatchRequest } from './role';

export class RoleAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: RoleCreateRequest, opts?: RequestOptions): Promise<Role> {
    return ambientFetch<Role>(this.config, 'POST', '/roles', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Role> {
    return ambientFetch<Role>(this.config, 'GET', `/roles/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<RoleList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<RoleList>(this.config, 'GET', `/roles${qs}`, undefined, opts);
  }
  async update(id: string, patch: RolePatchRequest, opts?: RequestOptions): Promise<Role> {
    return ambientFetch<Role>(this.config, 'PATCH', `/roles/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/roles/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Role> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
