// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 7ea37f5208cc0fc8e16933941e91c7a85bf61e94b0e4f7c8b1d4de918122a5a1
// Generated: 2026-06-29T17:10:10Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { ScheduledSession, ScheduledSessionList, ScheduledSessionCreateRequest, ScheduledSessionPatchRequest } from './scheduled_session';

export class ScheduledSessionAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    if (!this.config.project) {
      throw new Error('project is required for ScheduledSession operations');
    }
    return '/projects/{id}/scheduled-sessions'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: ScheduledSessionCreateRequest, opts?: RequestOptions): Promise<ScheduledSession> {
    return ambientFetch<ScheduledSession>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<ScheduledSession> {
    return ambientFetch<ScheduledSession>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ScheduledSessionList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<ScheduledSessionList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async update(id: string, patch: ScheduledSessionPatchRequest, opts?: RequestOptions): Promise<ScheduledSession> {
    return ambientFetch<ScheduledSession>(this.config, 'PATCH', `${this.basePath()}/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `${this.basePath()}/${id}`, undefined, opts);
  }

  async resume(id: string, opts?: RequestOptions): Promise<ScheduledSession> {
    return ambientFetch<ScheduledSession>(this.config, 'POST', `${this.basePath()}/${id}/resume`, undefined, opts);
  }

  async runs(id: string, opts?: RequestOptions): Promise<Record<string, unknown>> {
    return ambientFetch<Record<string, unknown>>(this.config, 'GET', `${this.basePath()}/${id}/runs`, undefined, opts);
  }

  async suspend(id: string, opts?: RequestOptions): Promise<ScheduledSession> {
    return ambientFetch<ScheduledSession>(this.config, 'POST', `${this.basePath()}/${id}/suspend`, undefined, opts);
  }

  async trigger(id: string, opts?: RequestOptions): Promise<Record<string, unknown>> {
    return ambientFetch<Record<string, unknown>>(this.config, 'POST', `${this.basePath()}/${id}/trigger`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<ScheduledSession> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
