// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: b033e32bec23ae0f0443bfe66148d0e29b42fa6bb0223ab012bdaf2860a2858e
// Generated: 2026-07-07T12:19:25Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { SessionEvent, SessionEventList, SessionEventCreateRequest } from './session_event';

export class SessionEventAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    if (!this.config.project) {
      throw new Error('project is required for SessionEvent operations');
    }
    return '/sessions/{id}/events/history'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: SessionEventCreateRequest, opts?: RequestOptions): Promise<SessionEvent> {
    return ambientFetch<SessionEvent>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<SessionEvent> {
    return ambientFetch<SessionEvent>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<SessionEventList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<SessionEventList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<SessionEvent> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
