// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: b30f3bd1a45276080577bd8a42c43e8a02968bf73b2042b7324122b25c73e5b1
// Generated: 2026-07-17T21:03:41Z

import type { ObjectReference, ListMeta } from './base';

export type SessionEvent = ObjectReference & {
  completed_at?: string;
  event_count: number;
  event_type: string;
  payload: string;
  seq: number;
  session_id: string;
};

export type SessionEventList = ListMeta & {
  items: SessionEvent[];
};

export type SessionEventCreateRequest = {
  event_type?: string;
  payload?: string;
};

export type SessionEventPatchRequest = {
};

export class SessionEventBuilder {
  private data: Record<string, unknown> = {};


  eventType(value: string): this {
    this.data['event_type'] = value;
    return this;
  }

  payload(value: string): this {
    this.data['payload'] = value;
    return this;
  }

  build(): SessionEventCreateRequest {
    return this.data as SessionEventCreateRequest;
  }
}

export class SessionEventPatchBuilder {
  private data: Record<string, unknown> = {};


  build(): SessionEventPatchRequest {
    return this.data as SessionEventPatchRequest;
  }
}
