// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: b2f4659285c47d15f89149857d020711a05eacfee25e684f7e09207fd5f178e3
// Generated: 2026-07-16T03:55:12Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { SessionMessage, SessionMessageList, SessionMessageCreateRequest } from './session_message';

export class SessionMessageAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    if (!this.config.project) {
      throw new Error('project is required for SessionMessage operations');
    }
    return '/sessions/{id}/messages'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: SessionMessageCreateRequest, opts?: RequestOptions): Promise<SessionMessage> {
    return ambientFetch<SessionMessage>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<SessionMessage> {
    return ambientFetch<SessionMessage>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<SessionMessageList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<SessionMessageList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<SessionMessage> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
