// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: f136081d1442aaec8e6d7e6b5db0a10b55f38cda7e3168930bc03e5eec439d17
// Generated: 2026-06-23T20:52:14Z

import type { ObjectReference, ListMeta } from './base';

export type SessionMessage = ObjectReference & {
  event_type: string;
  payload: string;
  seq: number;
  session_id: string;
};

export type SessionMessageList = ListMeta & {
  items: SessionMessage[];
};

export type SessionMessageCreateRequest = {
  event_type?: string;
  payload?: string;
};

export type SessionMessagePatchRequest = {
};

export class SessionMessageBuilder {
  private data: Record<string, unknown> = {};


  eventType(value: string): this {
    this.data['event_type'] = value;
    return this;
  }

  payload(value: string): this {
    this.data['payload'] = value;
    return this;
  }

  build(): SessionMessageCreateRequest {
    return this.data as SessionMessageCreateRequest;
  }
}

export class SessionMessagePatchBuilder {
  private data: Record<string, unknown> = {};


  build(): SessionMessagePatchRequest {
    return this.data as SessionMessagePatchRequest;
  }
}
