apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: frontend-oauth-deployment-patch.yaml
  target:
    kind: Deployment
    name: ambient-ui
- path: frontend-oauth-service-patch.yaml
  target:
    kind: Service
    name: ambient-ui-service
