// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: e8cbbb1535c7371667f381a83063a8e31ff4b13a28b782fef206b62a4e61f750
// Generated: 2026-07-02T20:49:37Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ApplicationAPI struct {
	client *Client
}

func (c *Client) Applications() *ApplicationAPI {
	return &ApplicationAPI{client: c}
}

func (a *ApplicationAPI) Create(ctx context.Context, resource *types.Application) (*types.Application, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal application: %w", err)
	}
	var result types.Application
	if err := a.client.do(ctx, http.MethodPost, "/applications", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ApplicationAPI) Get(ctx context.Context, id string) (*types.Application, error) {
	var result types.Application
	if err := a.client.do(ctx, http.MethodGet, "/applications/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ApplicationAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ApplicationList, error) {
	var result types.ApplicationList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/applications", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ApplicationAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Application, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Application
	if err := a.client.do(ctx, http.MethodPatch, "/applications/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ApplicationAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/applications/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *ApplicationAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Application] {
	return NewIterator(func(page int) (*types.ApplicationList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
