// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9aca8a0a98838cff1bba965fd3df124f91b80ab8059e441f6fff10863ccf6c35
// Generated: 2026-07-15T21:17:57Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ClusterAPI struct {
	client *Client
}

func (c *Client) Clusters() *ClusterAPI {
	return &ClusterAPI{client: c}
}

func (a *ClusterAPI) Create(ctx context.Context, resource *types.Cluster) (*types.Cluster, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal cluster: %w", err)
	}
	var result types.Cluster
	if err := a.client.do(ctx, http.MethodPost, "/clusters", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ClusterAPI) Get(ctx context.Context, id string) (*types.Cluster, error) {
	var result types.Cluster
	if err := a.client.do(ctx, http.MethodGet, "/clusters/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ClusterAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ClusterList, error) {
	var result types.ClusterList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/clusters", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ClusterAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Cluster, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Cluster
	if err := a.client.do(ctx, http.MethodPatch, "/clusters/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ClusterAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/clusters/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *ClusterAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Cluster] {
	return NewIterator(func(page int) (*types.ClusterList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
