// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 7ea37f5208cc0fc8e16933941e91c7a85bf61e94b0e4f7c8b1d4de918122a5a1
// Generated: 2026-06-29T17:10:10Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type SessionMessageAPI struct {
	client *Client
}

func (c *Client) SessionMessages() *SessionMessageAPI {
	return &SessionMessageAPI{client: c}
}
func (a *SessionMessageAPI) basePath() string {
	return strings.NewReplacer("{id}", url.PathEscape(a.client.project)).Replace("/sessions/{id}/messages")
}

func (a *SessionMessageAPI) Create(ctx context.Context, resource *types.SessionMessage) (*types.SessionMessage, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal session_message: %w", err)
	}
	var result types.SessionMessage
	if err := a.client.do(ctx, http.MethodPost, a.basePath(), body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionMessageAPI) Get(ctx context.Context, id string) (*types.SessionMessage, error) {
	var result types.SessionMessage
	if err := a.client.do(ctx, http.MethodGet, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionMessageAPI) List(ctx context.Context, opts *types.ListOptions) (*types.SessionMessageList, error) {
	var result types.SessionMessageList
	if err := a.client.doWithQuery(ctx, http.MethodGet, a.basePath(), nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *SessionMessageAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.SessionMessage] {
	return NewIterator(func(page int) (*types.SessionMessageList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
